
/****************************************************************
 *
 * Name      : pfgCyl.c
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.2 / Solaris 2.4
 *
 * Copyright (c) 1994-1995 by Sun MicroSystems, Inc.
 * All rights reserved.
 *
 ****************************************************************/

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>
#include <Xm/Xm.h>
#include <Xm/Protocols.h>

#include "tu_runtime.h"

#include <stdarg.h>

#include <stdio.h>
#include <stdlib.h>
#include "pfgCyl_ui.h"


#include <Xm/Form.h>
#include <Xm/Frame.h>
#include <Xm/Label.h>
#include <Xm/MessageB.h>
#include <Xm/MwmUtil.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/Text.h>
#include <Xm/TextF.h>


/* Local variables used when selecting screen & display */
static Display * sDisplay = NULL;
static Screen  * sScreen  = NULL;

/* forward declaration */
static void class_init(void);

extern void startLosingFocus(Widget widget,
                             tu_ccb_arg_p closure,
                             XtPointer calldata);
extern void sizeActivateCB(Widget widget,
                           tu_ccb_arg_p closure,
                           XtPointer calldata);
extern void mainMotionCB(Widget widget,
                         tu_ccb_arg_p closure,
                         XtPointer calldata);
extern void mountActivateCB(Widget widget,
                            tu_ccb_arg_p closure,
                            XtPointer calldata);
extern void mainFocusCB(Widget widget,
                        tu_ccb_arg_p closure,
                        XtPointer calldata);
extern void unregister_as_dropsite(Widget widget,
                                   tu_ccb_arg_p closure,
                                   XtPointer calldata);
extern void sizeLosingFocus(Widget widget,
                            tu_ccb_arg_p closure,
                            XtPointer calldata);
extern void sizeVerifyCB(Widget widget,
                         tu_ccb_arg_p closure,
                         XtPointer calldata);
extern void pfgHelp(Widget widget,
                    XtPointer closure,
                    XtPointer calldata);
extern void startActivateCB(Widget widget,
                            tu_ccb_arg_p closure,
                            XtPointer calldata);


/****************************************************************
 * get_constraint_widget:
 ****************************************************************/
static Widget get_constraint_widget(Widget child, Widget parent)
{
  Widget w;

  w = child;
  while (XtParent(w) != parent)
    w = XtParent(w);
  return (w);
}


/****************************************************************
 * put_client_data_arg:
 *    set up a client data argument.
 ****************************************************************/
static tu_ccb_arg_p put_client_data_arg(unsigned int cnt, ...)
{
  va_list pvar;
  int i;
  tu_ccb_arg_p rv;

  rv = (tu_ccb_arg_p) malloc(cnt*sizeof(tu_ccb_arg_t));
  if (rv == NULL) return NULL;

  va_start(pvar, cnt);

  for (i=0;i<cnt;i++) {
    rv[i].name = va_arg(pvar, char *);
    rv[i].value = va_arg(pvar, char *);
    rv[i].next = &rv[i+1];
  }
  va_end(pvar);
  rv[cnt-1].next = NULL;
  return rv;
}



/****************************************************************
 * class_init:
 *     Initializes the classes used by the user interface.
 ****************************************************************/
static void class_init(void)
{
  static int inited = 0;

  if (inited != 0)
    return;

  inited = 1;
  sDisplay = sDisplay;

  XtInitializeWidgetClass(xmFormWidgetClass);
  XtInitializeWidgetClass(xmTextWidgetClass);
  XtInitializeWidgetClass(xmTextFieldWidgetClass);
  XtInitializeWidgetClass(xmLabelWidgetClass);
  XtInitializeWidgetClass(xmFrameWidgetClass);
  XtInitializeWidgetClass(xmRowColumnWidgetClass);
  XtInitializeWidgetClass(xmMessageBoxWidgetClass);
  XtInitializeWidgetClass(xmPushButtonWidgetClass);
}



/****************************************************************
 *
 *  Main C code for presentation component
 *
 ****************************************************************/

/**************************************************************
 * tu_cyl_dialog_widget:
 **************************************************************/
Widget tu_cyl_dialog_widget(char    * name,
                            Widget    parent,
                            Widget ** warr_ret)
{
  Arg args[27];
  Widget widget_array[34];
  XmString xms;
  XtTranslations ttbl;
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmFormDialog *****************/
  widget_array[WI_CYL_DIALOG] =
    XmCreateFormDialog(parent, name, NULL, 0);

  /***************** panelhelpText : XmText *****************/
  n = 0;
  XtSetArg(args[n], XmNautoShowCursorPosition, False); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  XtSetArg(args[n], XmNeditMode, XmMULTI_LINE_EDIT); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNresizeHeight, True); n++;
  XtSetArg(args[n], XmNwordWrap, True); n++;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  XtSetArg(args[n], XmNmarginWidth, 18); n++;
  XtSetArg(args[n], XmNmarginHeight, 18); n++;
  XtSetArg(args[n], XmNvalue, "message_text"); n++;
  widget_array[WI_PANELHELPTEXT] =
    XmCreateText(widget_array[WI_CYL_DIALOG], "panelhelpText", args, n);

  /***************** cylForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 10); n++;
  XtSetArg(args[n], XmNmarginHeight, 10); n++;
  widget_array[WI_CYLFORM] =
    XmCreateForm(widget_array[WI_CYL_DIALOG], "cylForm", args, n);

  /***************** mainText : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNcolumns, 20); n++;
  widget_array[WI_MAINTEXT] =
    XmCreateTextField(widget_array[WI_CYLFORM], "mainText", args, n);

  /***************** recommendedForm : XmForm *****************/
  widget_array[WI_RECOMMENDEDFORM] =
    XmCreateForm(widget_array[WI_CYLFORM], "recommendedForm", NULL, 0);

  /***************** recommendedLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_END); n++;
  widget_array[WI_RECOMMENDEDLABEL] =
    XmCreateLabel(widget_array[WI_RECOMMENDEDFORM], "recommendedLabel", args, n);

  /***************** recommendedFrame : XmFrame *****************/
  n = 0;
  XtSetArg(args[n], XmNshadowType, XmSHADOW_IN); n++;
  widget_array[WI_RECOMMENDEDFRAME] =
    XmCreateFrame(widget_array[WI_RECOMMENDEDFORM], "recommendedFrame", args, n);

  /***************** recommendedValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNnavigationType, XmNONE); n++;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_END); n++;
  xms = tu_cvt_string_to_xmstring(" ");
  XtSetArg(args[n], XmNlabelString, xms); n++;
  widget_array[WI_RECOMMENDEDVALUE] =
    XmCreateLabel(widget_array[WI_RECOMMENDEDFRAME], "recommendedValue", args, n);

  if (xms) XmStringFree(xms);

  /***************** minimumForm : XmForm *****************/
  widget_array[WI_MINIMUMFORM] =
    XmCreateForm(widget_array[WI_CYLFORM], "minimumForm", NULL, 0);

  /***************** minimumLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_END); n++;
  widget_array[WI_MINIMUMLABEL] =
    XmCreateLabel(widget_array[WI_MINIMUMFORM], "minimumLabel", args, n);

  /***************** minimumFrame : XmFrame *****************/
  n = 0;
  XtSetArg(args[n], XmNshadowType, XmSHADOW_IN); n++;
  widget_array[WI_MINIMUMFRAME] =
    XmCreateFrame(widget_array[WI_MINIMUMFORM], "minimumFrame", args, n);

  /***************** minimumValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNnavigationType, XmNONE); n++;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_END); n++;
  xms = tu_cvt_string_to_xmstring(" ");
  XtSetArg(args[n], XmNlabelString, xms); n++;
  widget_array[WI_MINIMUMVALUE] =
    XmCreateLabel(widget_array[WI_MINIMUMFRAME], "minimumValue", args, n);

  if (xms) XmStringFree(xms);

  /***************** cylMatrixFrame : XmFrame *****************/
  n = 0;
  XtSetArg(args[n], XmNshadowType, XmSHADOW_OUT); n++;
  widget_array[WI_CYLMATRIXFRAME] =
    XmCreateFrame(widget_array[WI_CYLFORM], "cylMatrixFrame", args, n);

  /***************** cylMatrixForm : XmForm *****************/
  widget_array[WI_CYLMATRIXFORM] =
    XmCreateForm(widget_array[WI_CYLMATRIXFRAME], "cylMatrixForm", NULL, 0);

  /***************** cylEntryRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 5); n++;
  XtSetArg(args[n], XmNmarginHeight, 5); n++;
  XtSetArg(args[n], XmNentryAlignment, XmALIGNMENT_END); n++;
  XtSetArg(args[n], XmNspacing, 1); n++;
  XtSetArg(args[n], XmNnavigationType, XmNONE); n++;
  widget_array[WI_CYLENTRYROWCOLUMN] =
    XmCreateRowColumn(widget_array[WI_CYLMATRIXFORM], "cylEntryRowColumn", args, n);

  /***************** diskLabel : XmLabel *****************/
  widget_array[WI_DISKLABEL] =
    XmCreateLabel(widget_array[WI_CYLENTRYROWCOLUMN], "diskLabel", NULL, 0);

  /***************** headingLabel : XmLabel *****************/
  widget_array[WI_HEADINGLABEL] =
    XmCreateLabel(widget_array[WI_CYLENTRYROWCOLUMN], "headingLabel", NULL, 0);

  /***************** labelRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNentryAlignment, XmALIGNMENT_END); n++;
  widget_array[WI_LABELROWCOLUMN] =
    XmCreateRowColumn(widget_array[WI_CYLMATRIXFORM], "labelRowColumn", args, n);

  /***************** overheadLabel : XmLabel *****************/
  widget_array[WI_OVERHEADLABEL] =
    XmCreateLabel(widget_array[WI_LABELROWCOLUMN], "overheadLabel", NULL, 0);

  /***************** allocatedLabel : XmLabel *****************/
  widget_array[WI_ALLOCATEDLABEL] =
    XmCreateLabel(widget_array[WI_LABELROWCOLUMN], "allocatedLabel", NULL, 0);

  /***************** freeLabel : XmLabel *****************/
  widget_array[WI_FREELABEL] =
    XmCreateLabel(widget_array[WI_LABELROWCOLUMN], "freeLabel", NULL, 0);

  /***************** capacityLabel : XmLabel *****************/
  widget_array[WI_CAPACITYLABEL] =
    XmCreateLabel(widget_array[WI_LABELROWCOLUMN], "capacityLabel", NULL, 0);

  /***************** valueRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNentryAlignment, XmALIGNMENT_END); n++;
  widget_array[WI_VALUEROWCOLUMN] =
    XmCreateRowColumn(widget_array[WI_CYLMATRIXFORM], "valueRowColumn", args, n);

  /***************** overheadValue : XmLabel *****************/
  widget_array[WI_OVERHEADVALUE] =
    XmCreateLabel(widget_array[WI_VALUEROWCOLUMN], "overheadValue", NULL, 0);

  /***************** allocatedValue : XmLabel *****************/
  widget_array[WI_ALLOCATEDVALUE] =
    XmCreateLabel(widget_array[WI_VALUEROWCOLUMN], "allocatedValue", NULL, 0);

  /***************** freeValue : XmLabel *****************/
  widget_array[WI_FREEVALUE] =
    XmCreateLabel(widget_array[WI_VALUEROWCOLUMN], "freeValue", NULL, 0);

  /***************** capacityValue : XmLabel *****************/
  widget_array[WI_CAPACITYVALUE] =
    XmCreateLabel(widget_array[WI_VALUEROWCOLUMN], "capacityValue", NULL, 0);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdialogType, XmDIALOG_TEMPLATE); n++;
  widget_array[WI_MESSAGEBOX] =
    XmCreateMessageBox(widget_array[WI_CYL_DIALOG], "messageBox", args, n);

  /***************** okButton : XmPushButton *****************/
  widget_array[WI_OKBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "okButton", NULL, 0);

  /***************** loadButton : XmPushButton *****************/
  widget_array[WI_LOADBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "loadButton", NULL, 0);

  /***************** cancelButton : XmPushButton *****************/
  widget_array[WI_CANCELBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "cancelButton", NULL, 0);

  /***************** helpButton : XmPushButton *****************/
  widget_array[WI_HELPBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "helpButton", NULL, 0);

  /***************** button5 : XmPushButton *****************/
  widget_array[WI_BUTTON5] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "button5", NULL, 0);

  /* Terminate the widget array */
  widget_array[33] = NULL;


  /***************** panelhelpText : XmText *****************/
  n = 0;
  ttbl = XtParseTranslationTable("#override\n\
~Ctrl ~Meta<BtnDown>:\n\
~Ctrl ~Meta<BtnUp>:");
  XtOverrideTranslations(widget_array[WI_PANELHELPTEXT], ttbl);
  unregister_as_dropsite(widget_array[WI_PANELHELPTEXT],
                         NULL,
                         NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_PANELHELPTEXT], args, n);


  /***************** cylForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_PANELHELPTEXT]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_MESSAGEBOX]); n++;
  XtSetValues(widget_array[WI_CYLFORM], args, n);


  /***************** mainText : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_MAINTEXT],
                XmNfocusCallback,
                (XtCallbackProc)mainFocusCB,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_MAINTEXT],
                XmNmotionVerifyCallback,
                (XtCallbackProc)mainMotionCB,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_RECOMMENDEDFORM]); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_RECOMMENDEDFORM]); n++;
  XtSetValues(widget_array[WI_MAINTEXT], args, n);

  XtManageChild(widget_array[WI_MAINTEXT]);

  /***************** recommendedForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_MINIMUMFORM]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightOffset, 15); n++;
  XtSetValues(widget_array[WI_RECOMMENDEDFORM], args, n);


  /***************** recommendedLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_RECOMMENDEDLABEL], args, n);

  XtManageChild(widget_array[WI_RECOMMENDEDLABEL]);

  /***************** recommendedFrame : XmFrame *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_RECOMMENDEDLABEL]); n++;
  XtSetValues(widget_array[WI_RECOMMENDEDFRAME], args, n);

  XtManageChild(widget_array[WI_RECOMMENDEDVALUE]);
  XtManageChild(widget_array[WI_RECOMMENDEDFRAME]);
  XtManageChild(widget_array[WI_RECOMMENDEDFORM]);

  /***************** minimumForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MINIMUMFORM], args, n);


  /***************** minimumLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MINIMUMLABEL], args, n);

  XtManageChild(widget_array[WI_MINIMUMLABEL]);

  /***************** minimumFrame : XmFrame *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_MINIMUMLABEL]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MINIMUMFRAME], args, n);

  XtManageChild(widget_array[WI_MINIMUMVALUE]);
  XtManageChild(widget_array[WI_MINIMUMFRAME]);
  XtManageChild(widget_array[WI_MINIMUMFORM]);

  /***************** cylMatrixFrame : XmFrame *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_MINIMUMFORM]); n++;
  XtSetArg(args[n], XmNtopOffset, 10); n++;
  XtSetValues(widget_array[WI_CYLMATRIXFRAME], args, n);


  /***************** cylEntryRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_CYLENTRYROWCOLUMN], args, n);

  XtManageChild(widget_array[WI_DISKLABEL]);
  XtManageChild(widget_array[WI_HEADINGLABEL]);
  XtManageChild(widget_array[WI_CYLENTRYROWCOLUMN]);

  /***************** labelRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_VALUEROWCOLUMN]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_CYLENTRYROWCOLUMN]); n++;
  XtSetValues(widget_array[WI_LABELROWCOLUMN], args, n);

  XtManageChild(widget_array[WI_OVERHEADLABEL]);
  XtManageChild(widget_array[WI_ALLOCATEDLABEL]);
  XtManageChild(widget_array[WI_FREELABEL]);
  XtManageChild(widget_array[WI_CAPACITYLABEL]);
  XtManageChild(widget_array[WI_LABELROWCOLUMN]);

  /***************** valueRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_CYLENTRYROWCOLUMN]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_CYLENTRYROWCOLUMN]); n++;
  XtSetValues(widget_array[WI_VALUEROWCOLUMN], args, n);

  XtManageChild(widget_array[WI_OVERHEADVALUE]);
  XtManageChild(widget_array[WI_ALLOCATEDVALUE]);
  XtManageChild(widget_array[WI_FREEVALUE]);
  XtManageChild(widget_array[WI_CAPACITYVALUE]);
  XtManageChild(widget_array[WI_VALUEROWCOLUMN]);
  XtManageChild(widget_array[WI_CYLMATRIXFORM]);
  XtManageChild(widget_array[WI_CYLMATRIXFRAME]);
  XtManageChild(widget_array[WI_CYLFORM]);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdefaultButton, widget_array[WI_OKBUTTON]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MESSAGEBOX], args, n);

  XtManageChild(widget_array[WI_OKBUTTON]);
  XtManageChild(widget_array[WI_LOADBUTTON]);
  XtManageChild(widget_array[WI_CANCELBUTTON]);
  XtAddCallback(widget_array[WI_HELPBUTTON],
                XmNactivateCallback,
                pfgHelp,
                (XtPointer)"spotcylinder.r");

  XtManageChild(widget_array[WI_HELPBUTTON]);
  XtManageChild(widget_array[WI_MESSAGEBOX]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*34);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*34);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_CYL_DIALOG]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_CYL_DIALOG]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_CYL_DIALOG];
}


/**************************************************************
 * tu_cyl_slice_entry_widget:
 **************************************************************/
Widget tu_cyl_slice_entry_widget(char    * name,
                                 Widget    parent,
                                 Widget ** warr_ret)
{
  Arg args[17];
  Widget widget_array[7];
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNorientation, XmHORIZONTAL); n++;
  XtSetArg(args[n], XmNnavigationType, XmNONE); n++;
  XtSetArg(args[n], XmNmarginHeight, 0); n++;
  widget_array[WI_CYL_SLICE_ENTRY] =
    XmCreateRowColumn(parent, name, args, n);

  /***************** sliceLabel : XmLabel *****************/
  widget_array[WI_SLICELABEL] =
    XmCreateLabel(widget_array[WI_CYL_SLICE_ENTRY], "sliceLabel", NULL, 0);

  /***************** mountText : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNcolumns, 20); n++;
  XtSetArg(args[n], XmNnavigationType, XmNONE); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  widget_array[WI_MOUNTTEXT] =
    XmCreateTextField(widget_array[WI_CYL_SLICE_ENTRY], "mountText", args, n);

  /***************** sizeText : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNcolumns, 8); n++;
  XtSetArg(args[n], XmNmaxLength, 8); n++;
  XtSetArg(args[n], XmNnavigationType, XmNONE); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  widget_array[WI_SIZETEXT] =
    XmCreateTextField(widget_array[WI_CYL_SLICE_ENTRY], "sizeText", args, n);

  /***************** startText : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNmaxLength, 8); n++;
  XtSetArg(args[n], XmNcolumns, 8); n++;
  XtSetArg(args[n], XmNnavigationType, XmNONE); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  widget_array[WI_STARTTEXT] =
    XmCreateTextField(widget_array[WI_CYL_SLICE_ENTRY], "startText", args, n);

  /***************** endText : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNcolumns, 8); n++;
  XtSetArg(args[n], XmNeditable, False); n++;
  XtSetArg(args[n], XmNmaxLength, 8); n++;
  XtSetArg(args[n], XmNnavigationType, XmNONE); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  widget_array[WI_ENDTEXT] =
    XmCreateTextField(widget_array[WI_CYL_SLICE_ENTRY], "endText", args, n);

  /* Terminate the widget array */
  widget_array[6] = NULL;

  XtManageChild(widget_array[WI_SLICELABEL]);
  XtAddCallback(widget_array[WI_MOUNTTEXT],
                XmNactivateCallback,
                (XtCallbackProc)mountActivateCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_MOUNTTEXT]);
  XtAddCallback(widget_array[WI_SIZETEXT],
                XmNlosingFocusCallback,
                (XtCallbackProc)sizeLosingFocus,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_SIZETEXT],
                XmNactivateCallback,
                (XtCallbackProc)sizeActivateCB,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_SIZETEXT],
                XmNmodifyVerifyCallback,
                (XtCallbackProc)sizeVerifyCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_SIZETEXT]);
  XtAddCallback(widget_array[WI_STARTTEXT],
                XmNlosingFocusCallback,
                (XtCallbackProc)startLosingFocus,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_STARTTEXT],
                XmNactivateCallback,
                (XtCallbackProc)startActivateCB,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_STARTTEXT],
                XmNmodifyVerifyCallback,
                (XtCallbackProc)sizeVerifyCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_STARTTEXT]);
  XtManageChild(widget_array[WI_ENDTEXT]);
  XtManageChild(widget_array[WI_CYL_SLICE_ENTRY]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*7);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*7);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_CYL_SLICE_ENTRY]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_CYL_SLICE_ENTRY]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_CYL_SLICE_ENTRY];
}



/****************************************************************
 * create_method:
 *     This function creates a widget hierarchy using the
 *     functions generated above.
 ****************************************************************/
static Widget create_method(char               * temp,
                            char               * name,
                            Widget               parent,
                            Display            * disp,
                            Screen             * screen,
                            tu_template_descr  * retval)
{
  Widget w;

  sDisplay = disp;
  sScreen = screen;

  /* check each node against its name and call its
   * create function if appropriate */
  w = NULL;
  if (strcmp(temp, "cyl_dialog") == 0){
    w = tu_cyl_dialog_widget(name, parent, (Widget **)retval);
  }
  else if (strcmp(temp, "cyl_slice_entry") == 0){
    w = tu_cyl_slice_entry_widget(name, parent, (Widget **)retval);
  }

  sDisplay = NULL;
  sScreen = NULL;
  return w;
}

