
/****************************************************************
 *
 * Name      : pfgClients.c
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.2 / Solaris 2.4
 *
 * Copyright (c) 1994-1995 by Sun MicroSystems, Inc.
 * All rights reserved.
 *
 ****************************************************************/

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>
#include <Xm/Xm.h>
#include <Xm/Protocols.h>

#include "tu_runtime.h"

#include <stdarg.h>

#include <stdio.h>
#include <stdlib.h>
#include "pfgClients_ui.h"


#include <Xm/Form.h>
#include <Xm/Label.h>
#include <Xm/MessageB.h>
#include <Xm/MwmUtil.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/ScrolledW.h>
#include <Xm/Text.h>
#include <Xm/TextF.h>


/* Local variables used when selecting screen & display */
static Display * sDisplay = NULL;
static Screen  * sScreen  = NULL;

/* forward declaration */
static void class_init(void);

extern void setNumClientsCB(Widget widget,
                            tu_ccb_arg_p closure,
                            XtPointer calldata);
extern void pfgExit(Widget widget,
                    tu_ccb_arg_p closure,
                    XtPointer calldata);
extern void unregister_as_dropsite(Widget widget,
                                   tu_ccb_arg_p closure,
                                   XtPointer calldata);
extern void setSwapCB(Widget widget,
                      tu_ccb_arg_p closure,
                      XtPointer calldata);
extern void disklessGobackCB(Widget widget,
                             tu_ccb_arg_p closure,
                             XtPointer calldata);
extern void sizeVerifyCB(Widget widget,
                         tu_ccb_arg_p closure,
                         XtPointer calldata);
extern void pfgHelp(Widget widget,
                    XtPointer closure,
                    XtPointer calldata);


/****************************************************************
 * get_constraint_widget:
 ****************************************************************/
static Widget get_constraint_widget(Widget child, Widget parent)
{
  Widget w;

  w = child;
  while (XtParent(w) != parent)
    w = XtParent(w);
  return (w);
}


/****************************************************************
 * put_client_data_arg:
 *    set up a client data argument.
 ****************************************************************/
static tu_ccb_arg_p put_client_data_arg(unsigned int cnt, ...)
{
  va_list pvar;
  int i;
  tu_ccb_arg_p rv;

  rv = (tu_ccb_arg_p) malloc(cnt*sizeof(tu_ccb_arg_t));
  if (rv == NULL) return NULL;

  va_start(pvar, cnt);

  for (i=0;i<cnt;i++) {
    rv[i].name = va_arg(pvar, char *);
    rv[i].value = va_arg(pvar, char *);
    rv[i].next = &rv[i+1];
  }
  va_end(pvar);
  rv[cnt-1].next = NULL;
  return rv;
}



/****************************************************************
 * class_init:
 *     Initializes the classes used by the user interface.
 ****************************************************************/
static void class_init(void)
{
  static int inited = 0;

  if (inited != 0)
    return;

  inited = 1;
  sDisplay = sDisplay;

  XtInitializeWidgetClass(xmFormWidgetClass);
  XtInitializeWidgetClass(xmTextWidgetClass);
  XtInitializeWidgetClass(xmLabelWidgetClass);
  XtInitializeWidgetClass(xmTextFieldWidgetClass);
  XtInitializeWidgetClass(xmScrolledWindowWidgetClass);
  XtInitializeWidgetClass(xmRowColumnWidgetClass);
  XtInitializeWidgetClass(xmMessageBoxWidgetClass);
  XtInitializeWidgetClass(xmPushButtonWidgetClass);
}



/****************************************************************
 *
 *  Main C code for presentation component
 *
 ****************************************************************/

/**************************************************************
 * tu_diskless_dialog_widget:
 **************************************************************/
Widget tu_diskless_dialog_widget(char    * name,
                                 Widget    parent,
                                 Widget ** warr_ret)
{
  Arg args[26];
  Widget widget_array[19];
  XtTranslations ttbl;
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmFormDialog *****************/
  widget_array[WI_DISKLESS_DIALOG] =
    XmCreateFormDialog(parent, name, NULL, 0);

  /***************** panelhelpText : XmText *****************/
  n = 0;
  XtSetArg(args[n], XmNautoShowCursorPosition, False); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  XtSetArg(args[n], XmNeditMode, XmMULTI_LINE_EDIT); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNresizeHeight, True); n++;
  XtSetArg(args[n], XmNwordWrap, True); n++;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  XtSetArg(args[n], XmNmarginWidth, 18); n++;
  XtSetArg(args[n], XmNmarginHeight, 18); n++;
  XtSetArg(args[n], XmNvalue, "message_text"); n++;
  widget_array[WI_PANELHELPTEXT] =
    XmCreateText(widget_array[WI_DISKLESS_DIALOG], "panelhelpText", args, n);

  /***************** diskless_form : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNfractionBase, 5); n++;
  widget_array[WI_DISKLESS_FORM] =
    XmCreateForm(widget_array[WI_DISKLESS_DIALOG], "diskless_form", args, n);

  /***************** clientNumberLabelText : XmForm *****************/
  /* This field has been moved to file pfgInstallClients.pcd, it has been unmanaged on this screen. */
  widget_array[WI_CLIENTNUMBERLABELTEXT] =
    XmCreateForm(widget_array[WI_DISKLESS_FORM], "clientNumberLabelText", NULL, 0);

  /***************** clientNumberLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_END); n++;
  widget_array[WI_CLIENTNUMBERLABEL] =
    XmCreateLabel(widget_array[WI_CLIENTNUMBERLABELTEXT], "clientNumberLabel", args, n);

  /***************** clientNumberText : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNcolumns, 3); n++;
  XtSetArg(args[n], XmNmaxLength, 3); n++;
  widget_array[WI_CLIENTNUMBERTEXT] =
    XmCreateTextField(widget_array[WI_CLIENTNUMBERLABELTEXT], "clientNumberText", args, n);

  /***************** clientSwapLabelText : XmForm *****************/
  /* This field has been moved to pfgInstallClients.pcd, it has */
  /* been unmanaged on this screen. */
  widget_array[WI_CLIENTSWAPLABELTEXT] =
    XmCreateForm(widget_array[WI_DISKLESS_FORM], "clientSwapLabelText", NULL, 0);

  /***************** clientSwapLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_END); n++;
  widget_array[WI_CLIENTSWAPLABEL] =
    XmCreateLabel(widget_array[WI_CLIENTSWAPLABELTEXT], "clientSwapLabel", args, n);

  /***************** clientSwapText : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNmaxLength, 3); n++;
  XtSetArg(args[n], XmNcolumns, 3); n++;
  widget_array[WI_CLIENTSWAPTEXT] =
    XmCreateTextField(widget_array[WI_CLIENTSWAPLABELTEXT], "clientSwapText", args, n);

  /***************** architectureLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_ARCHITECTURELABEL] =
    XmCreateLabel(widget_array[WI_DISKLESS_FORM], "architectureLabel", args, n);

  /***************** architectureScrolledWindow : XmScrolledWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNscrollingPolicy, XmAUTOMATIC); n++;
  widget_array[WI_ARCHITECTURESCROLLEDWINDOW] =
    XmCreateScrolledWindow(widget_array[WI_DISKLESS_FORM], "architectureScrolledWindow", args, n);

  /***************** architectureRowColumn : XmRowColumn *****************/
  widget_array[WI_ARCHITECTUREROWCOLUMN] =
    XmCreateRowColumn(widget_array[WI_ARCHITECTURESCROLLEDWINDOW], "architectureRowColumn", NULL, 0);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdialogType, XmDIALOG_TEMPLATE); n++;
  widget_array[WI_MESSAGEBOX] =
    XmCreateMessageBox(widget_array[WI_DISKLESS_DIALOG], "messageBox", args, n);

  /***************** continueButton : XmPushButton *****************/
  widget_array[WI_CONTINUEBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "continueButton", NULL, 0);

  /***************** gobackButton : XmPushButton *****************/
  widget_array[WI_GOBACKBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "gobackButton", NULL, 0);

  /***************** exitButton : XmPushButton *****************/
  widget_array[WI_EXITBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "exitButton", NULL, 0);

  /***************** helpButton : XmPushButton *****************/
  widget_array[WI_HELPBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "helpButton", NULL, 0);

  /***************** button5 : XmPushButton *****************/
  widget_array[WI_BUTTON5] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "button5", NULL, 0);

  /* Terminate the widget array */
  widget_array[18] = NULL;


  /***************** panelhelpText : XmText *****************/
  n = 0;
  ttbl = XtParseTranslationTable("#override\n\
~Ctrl ~Meta<BtnDown>:\n\
~Ctrl ~Meta<BtnUp>:");
  XtOverrideTranslations(widget_array[WI_PANELHELPTEXT], ttbl);
  unregister_as_dropsite(widget_array[WI_PANELHELPTEXT],
                         NULL,
                         NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_PANELHELPTEXT], args, n);

  XtManageChild(widget_array[WI_PANELHELPTEXT]);

  /***************** diskless_form : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_PANELHELPTEXT]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_MESSAGEBOX]); n++;
  XtSetValues(widget_array[WI_DISKLESS_FORM], args, n);


  /***************** clientNumberLabelText : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_POSITION); n++;
  XtSetArg(args[n], XmNrightPosition, 4); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_CLIENTNUMBERLABELTEXT], args, n);


  /***************** clientNumberLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_CLIENTNUMBERTEXT]); n++;
  XtSetArg(args[n], XmNrightOffset, 5); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_CLIENTNUMBERTEXT]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_CLIENTNUMBERTEXT]); n++;
  XtSetValues(widget_array[WI_CLIENTNUMBERLABEL], args, n);

  XtManageChild(widget_array[WI_CLIENTNUMBERLABEL]);

  /***************** clientNumberText : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_CLIENTNUMBERTEXT],
                XmNactivateCallback,
                (XtCallbackProc)setNumClientsCB,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_CLIENTNUMBERTEXT],
                XmNlosingFocusCallback,
                (XtCallbackProc)setNumClientsCB,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_CLIENTNUMBERTEXT],
                XmNmodifyVerifyCallback,
                (XtCallbackProc)sizeVerifyCB,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_CLIENTNUMBERTEXT], args, n);

  XtManageChild(widget_array[WI_CLIENTNUMBERTEXT]);

  /***************** clientSwapLabelText : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_CLIENTNUMBERLABELTEXT]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_CLIENTNUMBERLABELTEXT]); n++;
  XtSetValues(widget_array[WI_CLIENTSWAPLABELTEXT], args, n);


  /***************** clientSwapLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_CLIENTSWAPTEXT]); n++;
  XtSetArg(args[n], XmNrightOffset, 5); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_CLIENTSWAPTEXT]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_CLIENTSWAPTEXT]); n++;
  XtSetValues(widget_array[WI_CLIENTSWAPLABEL], args, n);

  XtManageChild(widget_array[WI_CLIENTSWAPLABEL]);

  /***************** clientSwapText : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_CLIENTSWAPTEXT],
                XmNmodifyVerifyCallback,
                (XtCallbackProc)sizeVerifyCB,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_CLIENTSWAPTEXT],
                XmNlosingFocusCallback,
                (XtCallbackProc)setSwapCB,
                (XtPointer)NULL);

  XtAddCallback(widget_array[WI_CLIENTSWAPTEXT],
                XmNactivateCallback,
                (XtCallbackProc)setSwapCB,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_CLIENTSWAPTEXT], args, n);

  XtManageChild(widget_array[WI_CLIENTSWAPTEXT]);

  /***************** architectureLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_POSITION); n++;
  XtSetArg(args[n], XmNleftPosition, 1); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopOffset, 5); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_ARCHITECTURELABEL], args, n);

  XtManageChild(widget_array[WI_ARCHITECTURELABEL]);

  /***************** architectureScrolledWindow : XmScrolledWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_ARCHITECTURELABEL]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_POSITION); n++;
  XtSetArg(args[n], XmNleftPosition, 1); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_POSITION); n++;
  XtSetArg(args[n], XmNrightPosition, 4); n++;
  XtSetValues(widget_array[WI_ARCHITECTURESCROLLEDWINDOW], args, n);

  XtManageChild(widget_array[WI_ARCHITECTUREROWCOLUMN]);
  XtManageChild(widget_array[WI_ARCHITECTURESCROLLEDWINDOW]);
  XtManageChild(widget_array[WI_DISKLESS_FORM]);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdefaultButton, widget_array[WI_CONTINUEBUTTON]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MESSAGEBOX], args, n);

  XtManageChild(widget_array[WI_CONTINUEBUTTON]);
  XtAddCallback(widget_array[WI_GOBACKBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)disklessGobackCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_GOBACKBUTTON]);
  XtAddCallback(widget_array[WI_EXITBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)pfgExit,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_EXITBUTTON]);
  XtAddCallback(widget_array[WI_HELPBUTTON],
                XmNactivateCallback,
                pfgHelp,
                (XtPointer)"platform.h");

  XtManageChild(widget_array[WI_HELPBUTTON]);
  XtManageChild(widget_array[WI_MESSAGEBOX]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*19);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*19);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_DISKLESS_DIALOG]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_DISKLESS_DIALOG]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_DISKLESS_DIALOG];
}



/****************************************************************
 * create_method:
 *     This function creates a widget hierarchy using the
 *     functions generated above.
 ****************************************************************/
static Widget create_method(char               * temp,
                            char               * name,
                            Widget               parent,
                            Display            * disp,
                            Screen             * screen,
                            tu_template_descr  * retval)
{
  Widget w;

  sDisplay = disp;
  sScreen = screen;

  /* check each node against its name and call its
   * create function if appropriate */
  w = NULL;
  if (strcmp(temp, "diskless_dialog") == 0){
    w = tu_diskless_dialog_widget(name, parent, (Widget **)retval);
  }

  sDisplay = NULL;
  sScreen = NULL;
  return w;
}

