
/****************************************************************
 *
 * Name      : pfgLayout.c
 * Creator   : mtraub
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.1 / Solaris 2.3
 *
 ****************************************************************/

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>
#include <Xm/Xm.h>
#include <Xm/Protocols.h>

#include "tu_runtime.h"

#include <stdarg.h>

#include <stdio.h>
#include <stdlib.h>
#include "pfgLayout_ui.h"


#include <Xm/CascadeB.h>
#include <Xm/CascadeBG.h>
#include <Xm/Form.h>
#include <Xm/Label.h>
#include <Xm/MessageB.h>
#include <Xm/MwmUtil.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/ScrolledW.h>
#include <Xm/Text.h>
#include <Xm/TextF.h>
#include <Xm/ToggleB.h>


/* Local variables used when selecting screen & display */
static Display * sDisplay = NULL;
static Screen  * sScreen  = NULL;

/* forward declaration */
static void class_init(void);

extern void set_show_options(Widget widget,
                             tu_ccb_arg_p closure,
                             XtPointer calldata);
extern void set_disk_choice_any(Widget widget,
                                tu_ccb_arg_p closure,
                                XtPointer calldata);
extern void pfgExit(Widget widget,
                    tu_ccb_arg_p closure,
                    XtPointer calldata);
extern void layoutContinueCB(Widget widget,
                             tu_ccb_arg_p closure,
                             XtPointer calldata);
extern void unregister_as_dropsite(Widget widget,
                                   tu_ccb_arg_p closure,
                                   XtPointer calldata);
extern void set_slice_choice(Widget widget,
                             tu_ccb_arg_p closure,
                             XtPointer calldata);
extern void create_new_table_entry(Widget widget,
                                   tu_ccb_arg_p closure,
                                   XtPointer calldata);
extern void layoutCancelCB(Widget widget,
                           tu_ccb_arg_p closure,
                           XtPointer calldata);
extern void pfgHelp(Widget widget,
                    tu_ccb_arg_p closure,
                    XtPointer calldata);
extern void set_show_basic(Widget widget,
                           tu_ccb_arg_p closure,
                           XtPointer calldata);


/****************************************************************
 * get_constraint_widget:
 ****************************************************************/
static Widget get_constraint_widget(Widget child, Widget parent)
{
  Widget w;

  w = child;
  while (XtParent(w) != parent)
    w = XtParent(w);
  return (w);
}


/****************************************************************
 * put_client_data_arg:
 *    set up a client data argument.
 ****************************************************************/
static tu_ccb_arg_p put_client_data_arg(unsigned int cnt, ...)
{
  va_list pvar;
  int i;
  tu_ccb_arg_p rv;

  rv = (tu_ccb_arg_p) malloc(cnt*sizeof(tu_ccb_arg_t));
  if (rv == NULL) return NULL;

  va_start(pvar, cnt);

  for (i=0;i<cnt;i++) {
    rv[i].name = va_arg(pvar, char *);
    rv[i].value = va_arg(pvar, char *);
    rv[i].next = &rv[i+1];
  }
  va_end(pvar);
  rv[cnt-1].next = NULL;
  return rv;
}



/****************************************************************
 * class_init:
 *     Initializes the classes used by the user interface.
 *     This initialization can be turned off with the
 *     '-notinitclasses' (NOTINITCLASSES) option.
 ****************************************************************/
static void class_init(void)
{
  static int inited = 0;

  if (inited != 0)
    return;

  inited = 1;
  sDisplay = sDisplay;

  XtInitializeWidgetClass(xmFormWidgetClass);
  XtInitializeWidgetClass(xmTextWidgetClass);
  XtInitializeWidgetClass(xmLabelWidgetClass);
  XtInitializeWidgetClass(xmScrolledWindowWidgetClass);
  XtInitializeWidgetClass(xmRowColumnWidgetClass);
  XtInitializeWidgetClass(xmPushButtonWidgetClass);
  XtInitializeWidgetClass(xmMessageBoxWidgetClass);
  XtInitializeWidgetClass(xmToggleButtonWidgetClass);
  XtInitializeWidgetClass(xmTextFieldWidgetClass);
}



/****************************************************************
 *
 *  Main C code for presentation component
 *
 ****************************************************************/

/**************************************************************
 * tu_autoLayoutDialog_widget:
 **************************************************************/
Widget tu_autoLayoutDialog_widget(char    * name,
                                  Widget    parent,
                                  Widget ** warr_ret)
{
  Arg args[27];
  Widget widget_array[22];
  XtTranslations ttbl;
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmFormDialog *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_GROW); n++;
  XtSetArg(args[n], XmNmarginWidth, 15); n++;
  widget_array[WI_AUTOLAYOUTDIALOG] =
    XmCreateFormDialog(parent, name, args, n);

  /***************** panelhelpText : XmText *****************/
  n = 0;
  XtSetArg(args[n], XmNautoShowCursorPosition, False); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  XtSetArg(args[n], XmNeditMode, XmMULTI_LINE_EDIT); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNresizeHeight, True); n++;
  XtSetArg(args[n], XmNwordWrap, True); n++;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  XtSetArg(args[n], XmNmarginWidth, 18); n++;
  XtSetArg(args[n], XmNmarginHeight, 18); n++;
  XtSetArg(args[n], XmNvalue, "message_text"); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_PANELHELPTEXT] =
    XmCreateText(widget_array[WI_AUTOLAYOUTDIALOG], "panelhelpText", args, n);

  /***************** header_form : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNallowOverlap, False); n++;
  XtSetArg(args[n], XmNmarginHeight, 10); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_HEADER_FORM] =
    XmCreateForm(widget_array[WI_AUTOLAYOUTDIALOG], "header_form", args, n);

  /***************** basic_column_labels : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNallowOverlap, False); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_BASIC_COLUMN_LABELS] =
    XmCreateForm(widget_array[WI_HEADER_FORM], "basic_column_labels", args, n);

  /***************** slice_name_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SLICE_NAME_LABEL] =
    XmCreateLabel(widget_array[WI_BASIC_COLUMN_LABELS], "slice_name_label", args, n);

  /***************** rec_size_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_REC_SIZE_LABEL] =
    XmCreateLabel(widget_array[WI_BASIC_COLUMN_LABELS], "rec_size_label", args, n);

  /***************** create_size_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_CREATE_SIZE_LABEL] =
    XmCreateLabel(widget_array[WI_BASIC_COLUMN_LABELS], "create_size_label", args, n);

  /***************** options_column_labels : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNallowOverlap, False); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_OPTIONS_COLUMN_LABELS] =
    XmCreateForm(widget_array[WI_HEADER_FORM], "options_column_labels", args, n);

  /***************** disks_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_DISKS_LABEL] =
    XmCreateLabel(widget_array[WI_OPTIONS_COLUMN_LABELS], "disks_label", args, n);

  /***************** slices_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SLICES_LABEL] =
    XmCreateLabel(widget_array[WI_OPTIONS_COLUMN_LABELS], "slices_label", args, n);

  /***************** autoLayoutForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNverticalSpacing, 10); n++;
  XtSetArg(args[n], XmNmarginWidth, 10); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_AUTOLAYOUTFORM] =
    XmCreateForm(widget_array[WI_AUTOLAYOUTDIALOG], "autoLayoutForm", args, n);

  /***************** autoLayoutScrollWin : XmScrolledWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNheight, 200); n++;
  XtSetArg(args[n], XmNscrollingPolicy, XmAUTOMATIC); n++;
  XtSetArg(args[n], XmNwidth, 900); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_AUTOLAYOUTSCROLLWIN] =
    XmCreateScrolledWindow(widget_array[WI_AUTOLAYOUTFORM], "autoLayoutScrollWin", args, n);

  /***************** main_table_rc : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNadjustLast, False); n++;
  XtSetArg(args[n], XmNorientation, XmVERTICAL); n++;
  widget_array[WI_MAIN_TABLE_RC] =
    XmCreateRowColumn(widget_array[WI_AUTOLAYOUTSCROLLWIN], "main_table_rc", args, n);

  /***************** basic_button : XmPushButton *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_BASIC_BUTTON] =
    XmCreatePushButton(widget_array[WI_AUTOLAYOUTFORM], "basic_button", args, n);

  /***************** options_button : XmPushButton *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_OPTIONS_BUTTON] =
    XmCreatePushButton(widget_array[WI_AUTOLAYOUTFORM], "options_button", args, n);

  /***************** autoLayoutMessageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdialogType, XmDIALOG_TEMPLATE); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_AUTOLAYOUTMESSAGEBOX] =
    XmCreateMessageBox(widget_array[WI_AUTOLAYOUTDIALOG], "autoLayoutMessageBox", args, n);

  /***************** autoLayoutContinue : XmPushButton *****************/
  widget_array[WI_AUTOLAYOUTCONTINUE] =
    XmCreatePushButton(widget_array[WI_AUTOLAYOUTMESSAGEBOX], "autoLayoutContinue", NULL, 0);

  /***************** button_not_used : XmPushButton *****************/
  widget_array[WI_BUTTON_NOT_USED] =
    XmCreatePushButton(widget_array[WI_AUTOLAYOUTMESSAGEBOX], "button_not_used", NULL, 0);

  /***************** autoLayoutCancel : XmPushButton *****************/
  widget_array[WI_AUTOLAYOUTCANCEL] =
    XmCreatePushButton(widget_array[WI_AUTOLAYOUTMESSAGEBOX], "autoLayoutCancel", NULL, 0);

  /***************** autoLayoutExit : XmPushButton *****************/
  widget_array[WI_AUTOLAYOUTEXIT] =
    XmCreatePushButton(widget_array[WI_AUTOLAYOUTMESSAGEBOX], "autoLayoutExit", NULL, 0);

  /***************** autoLayoutHelp : XmPushButton *****************/
  widget_array[WI_AUTOLAYOUTHELP] =
    XmCreatePushButton(widget_array[WI_AUTOLAYOUTMESSAGEBOX], "autoLayoutHelp", NULL, 0);

  /* Terminate the widget array */
  widget_array[21] = NULL;


  /***************** panelhelpText : XmText *****************/
  n = 0;
  ttbl = XtParseTranslationTable("#override\n\
~Ctrl ~Meta<BtnDown>:\n\
~Ctrl ~Meta<BtnUp>:");
  XtOverrideTranslations(widget_array[WI_PANELHELPTEXT], ttbl);
  unregister_as_dropsite(widget_array[WI_PANELHELPTEXT],
                         NULL,
                         NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_PANELHELPTEXT], args, n);

  XtManageChild(widget_array[WI_PANELHELPTEXT]);

  /***************** header_form : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_PANELHELPTEXT]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_HEADER_FORM], args, n);


  /***************** basic_column_labels : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_BASIC_COLUMN_LABELS], args, n);


  /***************** slice_name_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SLICE_NAME_LABEL], args, n);

  XtManageChild(widget_array[WI_SLICE_NAME_LABEL]);

  /***************** rec_size_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_SLICE_NAME_LABEL]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_REC_SIZE_LABEL], args, n);

  XtManageChild(widget_array[WI_REC_SIZE_LABEL]);

  /***************** create_size_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_REC_SIZE_LABEL]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_CREATE_SIZE_LABEL], args, n);

  XtManageChild(widget_array[WI_CREATE_SIZE_LABEL]);
  XtManageChild(widget_array[WI_BASIC_COLUMN_LABELS]);

  /***************** options_column_labels : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_BASIC_COLUMN_LABELS]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_OPTIONS_COLUMN_LABELS], args, n);


  /***************** disks_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_DISKS_LABEL], args, n);

  XtManageChild(widget_array[WI_DISKS_LABEL]);

  /***************** slices_label : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_DISKS_LABEL]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SLICES_LABEL], args, n);

  XtManageChild(widget_array[WI_SLICES_LABEL]);
  XtManageChild(widget_array[WI_OPTIONS_COLUMN_LABELS]);
  XtManageChild(widget_array[WI_HEADER_FORM]);

  /***************** autoLayoutForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_HEADER_FORM]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_AUTOLAYOUTFORM], args, n);


  /***************** autoLayoutScrollWin : XmScrolledWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_AUTOLAYOUTSCROLLWIN], args, n);

  XtManageChild(widget_array[WI_MAIN_TABLE_RC]);
  XtManageChild(widget_array[WI_AUTOLAYOUTSCROLLWIN]);

  /***************** basic_button : XmPushButton *****************/
  n = 0;
  XtAddCallback(widget_array[WI_BASIC_BUTTON],
                XmNactivateCallback,
                (XtCallbackProc)set_show_options,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_AUTOLAYOUTSCROLLWIN]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_AUTOLAYOUTSCROLLWIN]); n++;
  XtSetValues(widget_array[WI_BASIC_BUTTON], args, n);


  /***************** options_button : XmPushButton *****************/
  n = 0;
  XtAddCallback(widget_array[WI_OPTIONS_BUTTON],
                XmNactivateCallback,
                (XtCallbackProc)set_show_basic,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_AUTOLAYOUTSCROLLWIN]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_AUTOLAYOUTSCROLLWIN]); n++;
  XtSetValues(widget_array[WI_OPTIONS_BUTTON], args, n);

  XtManageChild(widget_array[WI_AUTOLAYOUTFORM]);

  /***************** autoLayoutMessageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_AUTOLAYOUTFORM]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_AUTOLAYOUTMESSAGEBOX], args, n);

  XtAddCallback(widget_array[WI_AUTOLAYOUTCONTINUE],
                XmNactivateCallback,
                (XtCallbackProc)layoutContinueCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_AUTOLAYOUTCONTINUE]);
  XtAddCallback(widget_array[WI_AUTOLAYOUTCANCEL],
                XmNactivateCallback,
                (XtCallbackProc)layoutCancelCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_AUTOLAYOUTCANCEL]);
  XtAddCallback(widget_array[WI_AUTOLAYOUTEXIT],
                XmNactivateCallback,
                (XtCallbackProc)pfgExit,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_AUTOLAYOUTEXIT]);
  XtAddCallback(widget_array[WI_AUTOLAYOUTHELP],
                XmNactivateCallback,
                (XtCallbackProc)pfgHelp,
                (XtPointer)"autolayout.t");

  XtManageChild(widget_array[WI_AUTOLAYOUTHELP]);
  XtManageChild(widget_array[WI_AUTOLAYOUTMESSAGEBOX]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*22);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*22);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_AUTOLAYOUTDIALOG]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_AUTOLAYOUTDIALOG]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_AUTOLAYOUTDIALOG];
}


/**************************************************************
 * tu_full_table_entry_widget:
 **************************************************************/
Widget tu_full_table_entry_widget(char    * name,
                                  Widget    parent,
                                  Widget ** warr_ret)
{
  Arg args[19];
  Widget widget_array[21];
  XmString xms;
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNorientation, XmHORIZONTAL); n++;
  XtSetArg(args[n], XmNadjustLast, False); n++;
  widget_array[WI_FULL_TABLE_ENTRY] =
    XmCreateRowColumn(parent, name, args, n);

  /***************** basic_table_entry : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_NONE); n++;
  XtSetArg(args[n], XmNhorizontalSpacing, 30); n++;
  widget_array[WI_BASIC_TABLE_ENTRY] =
    XmCreateForm(widget_array[WI_FULL_TABLE_ENTRY], "basic_table_entry", args, n);

  /***************** select_slice_name : XmToggleButton *****************/
  n = 0;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_BEGINNING); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNspacing, 20); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SELECT_SLICE_NAME] =
    XmCreateToggleButton(widget_array[WI_BASIC_TABLE_ENTRY], "select_slice_name", args, n);

  /***************** recommended_size : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNwidth, 100); n++;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  xms = tu_cvt_string_to_xmstring("XXXXX");
  XtSetArg(args[n], XmNlabelString, xms); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_RECOMMENDED_SIZE] =
    XmCreateLabel(widget_array[WI_BASIC_TABLE_ENTRY], "recommended_size", args, n);

  if (xms) XmStringFree(xms);

  /***************** create_size : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNwidth, 100); n++;
  XtSetArg(args[n], XmNmaxLength, 4); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_CREATE_SIZE] =
    XmCreateTextField(widget_array[WI_BASIC_TABLE_ENTRY], "create_size", args, n);

  /***************** options_table_entry : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_NONE); n++;
  XtSetArg(args[n], XmNhorizontalSpacing, 30); n++;
  widget_array[WI_OPTIONS_TABLE_ENTRY] =
    XmCreateForm(widget_array[WI_FULL_TABLE_ENTRY], "options_table_entry", args, n);

  /***************** disk_option : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_DISK_OPTION] =
    XmCreateOptionMenu(widget_array[WI_OPTIONS_TABLE_ENTRY], "disk_option", args, n);

  /***************** disk_option_list : XmPulldownMenu *****************/
  widget_array[WI_DISK_OPTION_LIST] =
    XmCreatePulldownMenu(widget_array[WI_OPTIONS_TABLE_ENTRY], "disk_option_list", NULL, 0);
  {
    Arg args[1];
    XtSetArg(args[0], XmNsubMenuId, widget_array[WI_DISK_OPTION_LIST]);
    XtSetValues(widget_array[WI_DISK_OPTION], args, 1);
  }

  /***************** any_disk : XmPushButton *****************/
  widget_array[WI_ANY_DISK] =
    XmCreatePushButton(widget_array[WI_DISK_OPTION_LIST], "any_disk", NULL, 0);

  /***************** slice_option : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SLICE_OPTION] =
    XmCreateOptionMenu(widget_array[WI_OPTIONS_TABLE_ENTRY], "slice_option", args, n);

  /***************** slice_option_list : XmPulldownMenu *****************/
  widget_array[WI_SLICE_OPTION_LIST] =
    XmCreatePulldownMenu(widget_array[WI_OPTIONS_TABLE_ENTRY], "slice_option_list", NULL, 0);
  {
    Arg args[1];
    XtSetArg(args[0], XmNsubMenuId, widget_array[WI_SLICE_OPTION_LIST]);
    XtSetValues(widget_array[WI_SLICE_OPTION], args, 1);
  }

  /***************** any_slice : XmPushButton *****************/
  widget_array[WI_ANY_SLICE] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST], "any_slice", NULL, 0);

  /***************** slice_choice0 : XmPushButton *****************/
  widget_array[WI_SLICE_CHOICE0] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST], "slice_choice0", NULL, 0);

  /***************** slice_choice1 : XmPushButton *****************/
  widget_array[WI_SLICE_CHOICE1] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST], "slice_choice1", NULL, 0);

  /***************** slice_choice2 : XmPushButton *****************/
  widget_array[WI_SLICE_CHOICE2] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST], "slice_choice2", NULL, 0);

  /***************** slice_choice3 : XmPushButton *****************/
  widget_array[WI_SLICE_CHOICE3] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST], "slice_choice3", NULL, 0);

  /***************** slice_choice4 : XmPushButton *****************/
  widget_array[WI_SLICE_CHOICE4] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST], "slice_choice4", NULL, 0);

  /***************** slice_choice5 : XmPushButton *****************/
  widget_array[WI_SLICE_CHOICE5] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST], "slice_choice5", NULL, 0);

  /***************** slice_choice6 : XmPushButton *****************/
  widget_array[WI_SLICE_CHOICE6] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST], "slice_choice6", NULL, 0);

  /***************** slice_choice7 : XmPushButton *****************/
  widget_array[WI_SLICE_CHOICE7] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST], "slice_choice7", NULL, 0);

  /* Terminate the widget array */
  widget_array[20] = NULL;


  /***************** select_slice_name : XmToggleButton *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SELECT_SLICE_NAME], args, n);

  XtManageChild(widget_array[WI_SELECT_SLICE_NAME]);

  /***************** recommended_size : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_SELECT_SLICE_NAME]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_RECOMMENDED_SIZE], args, n);

  XtManageChild(widget_array[WI_RECOMMENDED_SIZE]);

  /***************** create_size : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_RECOMMENDED_SIZE]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_CREATE_SIZE], args, n);

  XtManageChild(widget_array[WI_CREATE_SIZE]);
  XtManageChild(widget_array[WI_BASIC_TABLE_ENTRY]);

  /***************** disk_option : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_DISK_OPTION], args, n);

  XtAddCallback(widget_array[WI_ANY_DISK],
                XmNactivateCallback,
                (XtCallbackProc)set_disk_choice_any,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_ANY_DISK]);
  XtManageChild(widget_array[WI_DISK_OPTION]);

  /***************** slice_option : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_DISK_OPTION]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SLICE_OPTION], args, n);

  XtAddCallback(widget_array[WI_ANY_SLICE],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"ANY");

  XtManageChild(widget_array[WI_ANY_SLICE]);
  XtAddCallback(widget_array[WI_SLICE_CHOICE0],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"0");

  XtManageChild(widget_array[WI_SLICE_CHOICE0]);
  XtAddCallback(widget_array[WI_SLICE_CHOICE1],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"1");

  XtManageChild(widget_array[WI_SLICE_CHOICE1]);
  XtAddCallback(widget_array[WI_SLICE_CHOICE2],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"2");

  XtManageChild(widget_array[WI_SLICE_CHOICE2]);
  XtAddCallback(widget_array[WI_SLICE_CHOICE3],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"3");

  XtManageChild(widget_array[WI_SLICE_CHOICE3]);
  XtAddCallback(widget_array[WI_SLICE_CHOICE4],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"4");

  XtManageChild(widget_array[WI_SLICE_CHOICE4]);
  XtAddCallback(widget_array[WI_SLICE_CHOICE5],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"5");

  XtManageChild(widget_array[WI_SLICE_CHOICE5]);
  XtAddCallback(widget_array[WI_SLICE_CHOICE6],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"6");

  XtManageChild(widget_array[WI_SLICE_CHOICE6]);
  XtAddCallback(widget_array[WI_SLICE_CHOICE7],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"7");

  XtManageChild(widget_array[WI_SLICE_CHOICE7]);
  XtManageChild(widget_array[WI_SLICE_OPTION]);
  XtManageChild(widget_array[WI_FULL_TABLE_ENTRY]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*21);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*21);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_FULL_TABLE_ENTRY]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_FULL_TABLE_ENTRY]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_FULL_TABLE_ENTRY];
}


/**************************************************************
 * tu_editable_table_entry_widget:
 **************************************************************/
Widget tu_editable_table_entry_widget(char    * name,
                                      Widget    parent,
                                      Widget ** warr_ret)
{
  Arg args[19];
  Widget widget_array[7];
  XmString xms;
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNhorizontalSpacing, 30); n++;
  widget_array[WI_EDITABLE_TABLE_ENTRY] =
    XmCreateForm(parent, name, args, n);

  /***************** recommended_size : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  XtSetArg(args[n], XmNwidth, 100); n++;
  xms = tu_cvt_string_to_xmstring("XXXXX");
  XtSetArg(args[n], XmNlabelString, xms); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_RECOMMENDED_SIZE1] =
    XmCreateLabel(widget_array[WI_EDITABLE_TABLE_ENTRY], "recommended_size", args, n);

  if (xms) XmStringFree(xms);

  /***************** create_size : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNwidth, 100); n++;
  XtSetArg(args[n], XmNmaxLength, 4); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_CREATE_SIZE1] =
    XmCreateTextField(widget_array[WI_EDITABLE_TABLE_ENTRY], "create_size", args, n);

  /***************** blank_name_entry : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_BLANK_NAME_ENTRY] =
    XmCreateForm(widget_array[WI_EDITABLE_TABLE_ENTRY], "blank_name_entry", args, n);

  /***************** select_slice_name : XmToggleButton *****************/
  n = 0;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_BEGINNING); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  xms = tu_cvt_string_to_xmstring(" ");
  XtSetArg(args[n], XmNlabelString, xms); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SELECT_SLICE_NAME1] =
    XmCreateToggleButton(widget_array[WI_BLANK_NAME_ENTRY], "select_slice_name", args, n);

  if (xms) XmStringFree(xms);

  /***************** new_slice_name : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_NEW_SLICE_NAME] =
    XmCreateTextField(widget_array[WI_BLANK_NAME_ENTRY], "new_slice_name", args, n);

  /* Terminate the widget array */
  widget_array[6] = NULL;


  /***************** recommended_size : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_BLANK_NAME_ENTRY]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_RECOMMENDED_SIZE1], args, n);

  XtManageChild(widget_array[WI_RECOMMENDED_SIZE1]);

  /***************** create_size : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_RECOMMENDED_SIZE1]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_CREATE_SIZE1], args, n);

  XtManageChild(widget_array[WI_CREATE_SIZE1]);

  /***************** blank_name_entry : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_BLANK_NAME_ENTRY], args, n);


  /***************** select_slice_name : XmToggleButton *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SELECT_SLICE_NAME1], args, n);

  XtManageChild(widget_array[WI_SELECT_SLICE_NAME1]);

  /***************** new_slice_name : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_NEW_SLICE_NAME],
                XmNactivateCallback,
                (XtCallbackProc)create_new_table_entry,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_SELECT_SLICE_NAME1]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_NEW_SLICE_NAME], args, n);

  XtManageChild(widget_array[WI_NEW_SLICE_NAME]);
  XtManageChild(widget_array[WI_BLANK_NAME_ENTRY]);
  XtManageChild(widget_array[WI_EDITABLE_TABLE_ENTRY]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*7);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*7);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_EDITABLE_TABLE_ENTRY]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_EDITABLE_TABLE_ENTRY]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_EDITABLE_TABLE_ENTRY];
}


/**************************************************************
 * tu_full_editable_entry_widget:
 **************************************************************/
Widget tu_full_editable_entry_widget(char    * name,
                                     Widget    parent,
                                     Widget ** warr_ret)
{
  Arg args[19];
  Widget widget_array[23];
  XmString xms;
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNorientation, XmHORIZONTAL); n++;
  XtSetArg(args[n], XmNadjustLast, True); n++;
  widget_array[WI_FULL_EDITABLE_ENTRY] =
    XmCreateRowColumn(parent, name, args, n);

  /***************** editable_table_entry : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNhorizontalSpacing, 30); n++;
  widget_array[WI_EDITABLE_TABLE_ENTRY1] =
    XmCreateForm(widget_array[WI_FULL_EDITABLE_ENTRY], "editable_table_entry", args, n);

  /***************** recommended_size : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  XtSetArg(args[n], XmNwidth, 100); n++;
  xms = tu_cvt_string_to_xmstring("XXXXX");
  XtSetArg(args[n], XmNlabelString, xms); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_RECOMMENDED_SIZE2] =
    XmCreateLabel(widget_array[WI_EDITABLE_TABLE_ENTRY1], "recommended_size", args, n);

  if (xms) XmStringFree(xms);

  /***************** create_size : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNwidth, 100); n++;
  XtSetArg(args[n], XmNmaxLength, 4); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_CREATE_SIZE2] =
    XmCreateTextField(widget_array[WI_EDITABLE_TABLE_ENTRY1], "create_size", args, n);

  /***************** blank_name_entry : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_BLANK_NAME_ENTRY1] =
    XmCreateForm(widget_array[WI_EDITABLE_TABLE_ENTRY1], "blank_name_entry", args, n);

  /***************** select_slice_name : XmToggleButton *****************/
  n = 0;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_BEGINNING); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  xms = tu_cvt_string_to_xmstring(" ");
  XtSetArg(args[n], XmNlabelString, xms); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SELECT_SLICE_NAME2] =
    XmCreateToggleButton(widget_array[WI_BLANK_NAME_ENTRY1], "select_slice_name", args, n);

  if (xms) XmStringFree(xms);

  /***************** new_slice_name : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_NEW_SLICE_NAME1] =
    XmCreateTextField(widget_array[WI_BLANK_NAME_ENTRY1], "new_slice_name", args, n);

  /***************** options_table_entry : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_NONE); n++;
  XtSetArg(args[n], XmNhorizontalSpacing, 30); n++;
  widget_array[WI_OPTIONS_TABLE_ENTRY1] =
    XmCreateForm(widget_array[WI_FULL_EDITABLE_ENTRY], "options_table_entry", args, n);

  /***************** disk_option : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_DISK_OPTION1] =
    XmCreateOptionMenu(widget_array[WI_OPTIONS_TABLE_ENTRY1], "disk_option", args, n);

  /***************** disk_option_list : XmPulldownMenu *****************/
  widget_array[WI_DISK_OPTION_LIST1] =
    XmCreatePulldownMenu(widget_array[WI_OPTIONS_TABLE_ENTRY1], "disk_option_list", NULL, 0);
  {
    Arg args[1];
    XtSetArg(args[0], XmNsubMenuId, widget_array[WI_DISK_OPTION_LIST1]);
    XtSetValues(widget_array[WI_DISK_OPTION1], args, 1);
  }

  /***************** any_disk : XmPushButton *****************/
  widget_array[WI_ANY_DISK1] =
    XmCreatePushButton(widget_array[WI_DISK_OPTION_LIST1], "any_disk", NULL, 0);

  /***************** slice_option : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SLICE_OPTION1] =
    XmCreateOptionMenu(widget_array[WI_OPTIONS_TABLE_ENTRY1], "slice_option", args, n);

  /***************** slice_option_list : XmPulldownMenu *****************/
  widget_array[WI_SLICE_OPTION_LIST1] =
    XmCreatePulldownMenu(widget_array[WI_OPTIONS_TABLE_ENTRY1], "slice_option_list", NULL, 0);
  {
    Arg args[1];
    XtSetArg(args[0], XmNsubMenuId, widget_array[WI_SLICE_OPTION_LIST1]);
    XtSetValues(widget_array[WI_SLICE_OPTION1], args, 1);
  }

  /***************** any_slice : XmPushButton *****************/
  widget_array[WI_ANY_SLICE1] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST1], "any_slice", NULL, 0);

  /***************** slice_choice0 : XmPushButton *****************/
  widget_array[WI_SLICE_CHOICE8] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST1], "slice_choice0", NULL, 0);

  /***************** slice_choice1 : XmPushButton *****************/
  widget_array[WI_SLICE_CHOICE9] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST1], "slice_choice1", NULL, 0);

  /***************** slice_choice2 : XmPushButton *****************/
  widget_array[WI_SLICE_CHOICE10] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST1], "slice_choice2", NULL, 0);

  /***************** slice_choice3 : XmPushButton *****************/
  widget_array[WI_SLICE_CHOICE11] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST1], "slice_choice3", NULL, 0);

  /***************** slice_choice4 : XmPushButton *****************/
  widget_array[WI_SLICE_CHOICE12] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST1], "slice_choice4", NULL, 0);

  /***************** slice_choice5 : XmPushButton *****************/
  widget_array[WI_SLICE_CHOICE13] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST1], "slice_choice5", NULL, 0);

  /***************** slice_choice6 : XmPushButton *****************/
  widget_array[WI_SLICE_CHOICE14] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST1], "slice_choice6", NULL, 0);

  /***************** slice_choice7 : XmPushButton *****************/
  widget_array[WI_SLICE_CHOICE15] =
    XmCreatePushButton(widget_array[WI_SLICE_OPTION_LIST1], "slice_choice7", NULL, 0);

  /* Terminate the widget array */
  widget_array[22] = NULL;


  /***************** recommended_size : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_BLANK_NAME_ENTRY1]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_RECOMMENDED_SIZE2], args, n);

  XtManageChild(widget_array[WI_RECOMMENDED_SIZE2]);

  /***************** create_size : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_RECOMMENDED_SIZE2]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_CREATE_SIZE2], args, n);

  XtManageChild(widget_array[WI_CREATE_SIZE2]);

  /***************** blank_name_entry : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_BLANK_NAME_ENTRY1], args, n);


  /***************** select_slice_name : XmToggleButton *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SELECT_SLICE_NAME2], args, n);

  XtManageChild(widget_array[WI_SELECT_SLICE_NAME2]);

  /***************** new_slice_name : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_NEW_SLICE_NAME1],
                XmNactivateCallback,
                (XtCallbackProc)create_new_table_entry,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_SELECT_SLICE_NAME2]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_NEW_SLICE_NAME1], args, n);

  XtManageChild(widget_array[WI_NEW_SLICE_NAME1]);
  XtManageChild(widget_array[WI_BLANK_NAME_ENTRY1]);
  XtManageChild(widget_array[WI_EDITABLE_TABLE_ENTRY1]);

  /***************** disk_option : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_DISK_OPTION1], args, n);

  XtAddCallback(widget_array[WI_ANY_DISK1],
                XmNactivateCallback,
                (XtCallbackProc)set_disk_choice_any,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_ANY_DISK1]);
  XtManageChild(widget_array[WI_DISK_OPTION1]);

  /***************** slice_option : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_DISK_OPTION1]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SLICE_OPTION1], args, n);

  XtAddCallback(widget_array[WI_ANY_SLICE1],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"ANY");

  XtManageChild(widget_array[WI_ANY_SLICE1]);
  XtAddCallback(widget_array[WI_SLICE_CHOICE8],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"0");

  XtManageChild(widget_array[WI_SLICE_CHOICE8]);
  XtAddCallback(widget_array[WI_SLICE_CHOICE9],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"1");

  XtManageChild(widget_array[WI_SLICE_CHOICE9]);
  XtAddCallback(widget_array[WI_SLICE_CHOICE10],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"2");

  XtManageChild(widget_array[WI_SLICE_CHOICE10]);
  XtAddCallback(widget_array[WI_SLICE_CHOICE11],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"3");

  XtManageChild(widget_array[WI_SLICE_CHOICE11]);
  XtAddCallback(widget_array[WI_SLICE_CHOICE12],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"4");

  XtManageChild(widget_array[WI_SLICE_CHOICE12]);
  XtAddCallback(widget_array[WI_SLICE_CHOICE13],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"5");

  XtManageChild(widget_array[WI_SLICE_CHOICE13]);
  XtAddCallback(widget_array[WI_SLICE_CHOICE14],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"6");

  XtManageChild(widget_array[WI_SLICE_CHOICE14]);
  XtAddCallback(widget_array[WI_SLICE_CHOICE15],
                XmNactivateCallback,
                (XtCallbackProc)set_slice_choice,
                (XtPointer)"7");

  XtManageChild(widget_array[WI_SLICE_CHOICE15]);
  XtManageChild(widget_array[WI_SLICE_OPTION1]);
  XtManageChild(widget_array[WI_FULL_EDITABLE_ENTRY]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*23);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*23);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_FULL_EDITABLE_ENTRY]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_FULL_EDITABLE_ENTRY]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_FULL_EDITABLE_ENTRY];
}



/****************************************************************
 * create_method:
 *     This function creates a widget hierarchy using the
 *     functions generated above.
 ****************************************************************/
static Widget create_method(char               * temp,
                            char               * name,
                            Widget               parent,
                            Display            * disp,
                            Screen             * screen,
                            tu_template_descr  * retval)
{
  Widget w;

  sDisplay = disp;
  sScreen = screen;

  /* check each node against its name and call its
   * create function if appropriate */
  w = NULL;
  if (strcmp(temp, "autoLayoutDialog") == 0){
    w = tu_autoLayoutDialog_widget(name, parent, (Widget **)retval);
  }
  else if (strcmp(temp, "full_table_entry") == 0){
    w = tu_full_table_entry_widget(name, parent, (Widget **)retval);
  }
  else if (strcmp(temp, "editable_table_entry") == 0){
    w = tu_editable_table_entry_widget(name, parent, (Widget **)retval);
  }
  else if (strcmp(temp, "full_editable_entry") == 0){
    w = tu_full_editable_entry_widget(name, parent, (Widget **)retval);
  }

  sDisplay = NULL;
  sScreen = NULL;
  return w;
}

