
/****************************************************************
 *
 * Name      : pfgPreserve.c
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.2 / Solaris 2.4
 *
 * Copyright (c) 1994-1995 by Sun MicroSystems, Inc.
 * All rights reserved.
 *
 ****************************************************************/

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>
#include <Xm/Xm.h>
#include <Xm/Protocols.h>

#include "tu_runtime.h"

#include <stdarg.h>

#include <stdio.h>
#include <stdlib.h>
#include "pfgPreserve_ui.h"


#include <Xm/Form.h>
#include <Xm/Frame.h>
#include <Xm/Label.h>
#include <Xm/MessageB.h>
#include <Xm/MwmUtil.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/ScrolledW.h>
#include <Xm/Text.h>
#include <Xm/TextF.h>
#include <Xm/ToggleB.h>


/* Local variables used when selecting screen & display */
static Display * sDisplay = NULL;
static Screen  * sScreen  = NULL;

/* forward declaration */
static void class_init(void);

extern void preserveCancelCB(Widget widget,
                             tu_ccb_arg_p closure,
                             XtPointer calldata);
extern void unregister_as_dropsite(Widget widget,
                                   tu_ccb_arg_p closure,
                                   XtPointer calldata);
extern void preserveToggleCB(Widget widget,
                             tu_ccb_arg_p closure,
                             XtPointer calldata);
extern void pfgHelp(Widget widget,
                    XtPointer closure,
                    XtPointer calldata);
extern void mountVerifyCB(Widget widget,
                          tu_ccb_arg_p closure,
                          XtPointer calldata);


/****************************************************************
 * get_constraint_widget:
 ****************************************************************/
static Widget get_constraint_widget(Widget child, Widget parent)
{
  Widget w;

  w = child;
  while (XtParent(w) != parent)
    w = XtParent(w);
  return (w);
}


/****************************************************************
 * put_client_data_arg:
 *    set up a client data argument.
 ****************************************************************/
static tu_ccb_arg_p put_client_data_arg(unsigned int cnt, ...)
{
  va_list pvar;
  int i;
  tu_ccb_arg_p rv;

  rv = (tu_ccb_arg_p) malloc(cnt*sizeof(tu_ccb_arg_t));
  if (rv == NULL) return NULL;

  va_start(pvar, cnt);

  for (i=0;i<cnt;i++) {
    rv[i].name = va_arg(pvar, char *);
    rv[i].value = va_arg(pvar, char *);
    rv[i].next = &rv[i+1];
  }
  va_end(pvar);
  rv[cnt-1].next = NULL;
  return rv;
}



/****************************************************************
 * class_init:
 *     Initializes the classes used by the user interface.
 ****************************************************************/
static void class_init(void)
{
  static int inited = 0;

  if (inited != 0)
    return;

  inited = 1;
  sDisplay = sDisplay;

  XtInitializeWidgetClass(xmFrameWidgetClass);
  XtInitializeWidgetClass(xmFormWidgetClass);
  XtInitializeWidgetClass(xmLabelWidgetClass);
  XtInitializeWidgetClass(xmTextFieldWidgetClass);
  XtInitializeWidgetClass(xmToggleButtonWidgetClass);
  XtInitializeWidgetClass(xmTextWidgetClass);
  XtInitializeWidgetClass(xmScrolledWindowWidgetClass);
  XtInitializeWidgetClass(xmRowColumnWidgetClass);
  XtInitializeWidgetClass(xmMessageBoxWidgetClass);
  XtInitializeWidgetClass(xmPushButtonWidgetClass);
}



/****************************************************************
 *
 *  Main C code for presentation component
 *
 ****************************************************************/

/**************************************************************
 * tu_preserve_entry_widget:
 **************************************************************/
Widget tu_preserve_entry_widget(char    * name,
                                Widget    parent,
                                Widget ** warr_ret)
{
  Arg args[17];
  Widget widget_array[7];
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmFrame *****************/
  widget_array[WI_PRESERVE_ENTRY] =
    XmCreateFrame(parent, name, NULL, 0);

  /***************** preserveEntryForm : XmForm *****************/
  widget_array[WI_PRESERVEENTRYFORM] =
    XmCreateForm(widget_array[WI_PRESERVE_ENTRY], "preserveEntryForm", NULL, 0);

  /***************** preserveSliceLabel : XmLabel *****************/
  widget_array[WI_PRESERVESLICELABEL] =
    XmCreateLabel(widget_array[WI_PRESERVEENTRYFORM], "preserveSliceLabel", NULL, 0);

  /***************** preserveMountText : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNcolumns, 32); n++;
  widget_array[WI_PRESERVEMOUNTTEXT] =
    XmCreateTextField(widget_array[WI_PRESERVEENTRYFORM], "preserveMountText", args, n);

  /***************** preserveSizeLabel : XmLabel *****************/
  widget_array[WI_PRESERVESIZELABEL] =
    XmCreateLabel(widget_array[WI_PRESERVEENTRYFORM], "preserveSizeLabel", NULL, 0);

  /***************** preserveToggleButton : XmToggleButton *****************/
  widget_array[WI_PRESERVETOGGLEBUTTON] =
    XmCreateToggleButton(widget_array[WI_PRESERVEENTRYFORM], "preserveToggleButton", NULL, 0);

  /* Terminate the widget array */
  widget_array[6] = NULL;


  /***************** preserveSliceLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_PRESERVEMOUNTTEXT]); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_PRESERVEMOUNTTEXT]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_PRESERVEMOUNTTEXT]); n++;
  XtSetValues(widget_array[WI_PRESERVESLICELABEL], args, n);

  XtManageChild(widget_array[WI_PRESERVESLICELABEL]);

  /***************** preserveMountText : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_PRESERVEMOUNTTEXT],
                XmNmodifyVerifyCallback,
                (XtCallbackProc)mountVerifyCB,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_PRESERVESIZELABEL]); n++;
  XtSetValues(widget_array[WI_PRESERVEMOUNTTEXT], args, n);

  XtManageChild(widget_array[WI_PRESERVEMOUNTTEXT]);

  /***************** preserveSizeLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_PRESERVETOGGLEBUTTON]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_PRESERVETOGGLEBUTTON]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_PRESERVETOGGLEBUTTON]); n++;
  XtSetValues(widget_array[WI_PRESERVESIZELABEL], args, n);

  XtManageChild(widget_array[WI_PRESERVESIZELABEL]);

  /***************** preserveToggleButton : XmToggleButton *****************/
  n = 0;
  XtAddCallback(widget_array[WI_PRESERVETOGGLEBUTTON],
                XmNvalueChangedCallback,
                (XtCallbackProc)preserveToggleCB,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_PRESERVETOGGLEBUTTON], args, n);

  XtManageChild(widget_array[WI_PRESERVETOGGLEBUTTON]);
  XtManageChild(widget_array[WI_PRESERVEENTRYFORM]);
  XtManageChild(widget_array[WI_PRESERVE_ENTRY]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*7);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*7);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_PRESERVE_ENTRY]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_PRESERVE_ENTRY]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_PRESERVE_ENTRY];
}


/**************************************************************
 * tu_preserve_dialog_widget:
 **************************************************************/
Widget tu_preserve_dialog_widget(char    * name,
                                 Widget    parent,
                                 Widget ** warr_ret)
{
  Arg args[26];
  Widget widget_array[16];
  XtTranslations ttbl;
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmFormDialog *****************/
  widget_array[WI_PRESERVE_DIALOG] =
    XmCreateFormDialog(parent, name, NULL, 0);

  /***************** panelhelpText : XmText *****************/
  n = 0;
  XtSetArg(args[n], XmNautoShowCursorPosition, False); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  XtSetArg(args[n], XmNeditMode, XmMULTI_LINE_EDIT); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNresizeHeight, True); n++;
  XtSetArg(args[n], XmNwordWrap, True); n++;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  XtSetArg(args[n], XmNmarginWidth, 18); n++;
  XtSetArg(args[n], XmNmarginHeight, 18); n++;
  XtSetArg(args[n], XmNvalue, "message_text"); n++;
  widget_array[WI_PANELHELPTEXT] =
    XmCreateText(widget_array[WI_PRESERVE_DIALOG], "panelhelpText", args, n);

  /***************** preserveForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 20); n++;
  widget_array[WI_PRESERVEFORM] =
    XmCreateForm(widget_array[WI_PRESERVE_DIALOG], "preserveForm", args, n);

  /***************** sliceColumnLabel : XmLabel *****************/
  widget_array[WI_SLICECOLUMNLABEL] =
    XmCreateLabel(widget_array[WI_PRESERVEFORM], "sliceColumnLabel", NULL, 0);

  /***************** fileSystemColumnLabel : XmLabel *****************/
  widget_array[WI_FILESYSTEMCOLUMNLABEL] =
    XmCreateLabel(widget_array[WI_PRESERVEFORM], "fileSystemColumnLabel", NULL, 0);

  /***************** sizeColumnLabel : XmLabel *****************/
  widget_array[WI_SIZECOLUMNLABEL] =
    XmCreateLabel(widget_array[WI_PRESERVEFORM], "sizeColumnLabel", NULL, 0);

  /***************** preserveColumnLabel : XmLabel *****************/
  widget_array[WI_PRESERVECOLUMNLABEL] =
    XmCreateLabel(widget_array[WI_PRESERVEFORM], "preserveColumnLabel", NULL, 0);

  /***************** preserveScrolledWindow : XmScrolledWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNscrollingPolicy, XmAUTOMATIC); n++;
  widget_array[WI_PRESERVESCROLLEDWINDOW] =
    XmCreateScrolledWindow(widget_array[WI_PRESERVEFORM], "preserveScrolledWindow", args, n);

  /***************** preserveRowColumn : XmRowColumn *****************/
  widget_array[WI_PRESERVEROWCOLUMN] =
    XmCreateRowColumn(widget_array[WI_PRESERVESCROLLEDWINDOW], "preserveRowColumn", NULL, 0);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdialogType, XmDIALOG_TEMPLATE); n++;
  widget_array[WI_MESSAGEBOX] =
    XmCreateMessageBox(widget_array[WI_PRESERVE_DIALOG], "messageBox", args, n);

  /***************** continueButton : XmPushButton *****************/
  widget_array[WI_CONTINUEBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "continueButton", NULL, 0);

  /***************** cancelButton : XmPushButton *****************/
  widget_array[WI_CANCELBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "cancelButton", NULL, 0);

  /***************** helpButton : XmPushButton *****************/
  widget_array[WI_HELPBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "helpButton", NULL, 0);

  /***************** button4 : XmPushButton *****************/
  widget_array[WI_BUTTON4] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "button4", NULL, 0);

  /***************** button5 : XmPushButton *****************/
  widget_array[WI_BUTTON5] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "button5", NULL, 0);

  /* Terminate the widget array */
  widget_array[15] = NULL;


  /***************** panelhelpText : XmText *****************/
  n = 0;
  ttbl = XtParseTranslationTable("#override\n\
~Ctrl ~Meta<BtnDown>:\n\
~Ctrl ~Meta<BtnUp>:");
  XtOverrideTranslations(widget_array[WI_PANELHELPTEXT], ttbl);
  unregister_as_dropsite(widget_array[WI_PANELHELPTEXT],
                         NULL,
                         NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_PANELHELPTEXT], args, n);

  XtManageChild(widget_array[WI_PANELHELPTEXT]);

  /***************** preserveForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_PANELHELPTEXT]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_MESSAGEBOX]); n++;
  XtSetValues(widget_array[WI_PRESERVEFORM], args, n);


  /***************** sliceColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SLICECOLUMNLABEL], args, n);

  XtManageChild(widget_array[WI_SLICECOLUMNLABEL]);

  /***************** fileSystemColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_SLICECOLUMNLABEL]); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_SLICECOLUMNLABEL]); n++;
  XtSetValues(widget_array[WI_FILESYSTEMCOLUMNLABEL], args, n);

  XtManageChild(widget_array[WI_FILESYSTEMCOLUMNLABEL]);

  /***************** sizeColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_FILESYSTEMCOLUMNLABEL]); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_FILESYSTEMCOLUMNLABEL]); n++;
  XtSetValues(widget_array[WI_SIZECOLUMNLABEL], args, n);

  XtManageChild(widget_array[WI_SIZECOLUMNLABEL]);

  /***************** preserveColumnLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_SIZECOLUMNLABEL]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_SIZECOLUMNLABEL]); n++;
  XtSetValues(widget_array[WI_PRESERVECOLUMNLABEL], args, n);

  XtManageChild(widget_array[WI_PRESERVECOLUMNLABEL]);

  /***************** preserveScrolledWindow : XmScrolledWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_SLICECOLUMNLABEL]); n++;
  XtSetValues(widget_array[WI_PRESERVESCROLLEDWINDOW], args, n);

  XtManageChild(widget_array[WI_PRESERVEROWCOLUMN]);
  XtManageChild(widget_array[WI_PRESERVESCROLLEDWINDOW]);
  XtManageChild(widget_array[WI_PRESERVEFORM]);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdefaultButton, widget_array[WI_CONTINUEBUTTON]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MESSAGEBOX], args, n);

  XtManageChild(widget_array[WI_CONTINUEBUTTON]);
  XtAddCallback(widget_array[WI_CANCELBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)preserveCancelCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_CANCELBUTTON]);
  XtAddCallback(widget_array[WI_HELPBUTTON],
                XmNactivateCallback,
                pfgHelp,
                (XtPointer)"preserve.h");

  XtManageChild(widget_array[WI_HELPBUTTON]);
  XtManageChild(widget_array[WI_MESSAGEBOX]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*16);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*16);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_PRESERVE_DIALOG]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_PRESERVE_DIALOG]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_PRESERVE_DIALOG];
}



/****************************************************************
 * create_method:
 *     This function creates a widget hierarchy using the
 *     functions generated above.
 ****************************************************************/
static Widget create_method(char               * temp,
                            char               * name,
                            Widget               parent,
                            Display            * disp,
                            Screen             * screen,
                            tu_template_descr  * retval)
{
  Widget w;

  sDisplay = disp;
  sScreen = screen;

  /* check each node against its name and call its
   * create function if appropriate */
  w = NULL;
  if (strcmp(temp, "preserve_entry") == 0){
    w = tu_preserve_entry_widget(name, parent, (Widget **)retval);
  }
  else if (strcmp(temp, "preserve_dialog") == 0){
    w = tu_preserve_dialog_widget(name, parent, (Widget **)retval);
  }

  sDisplay = NULL;
  sScreen = NULL;
  return w;
}

