
/****************************************************************
 *
 * Name      : pfgRemote.c
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.2 / Solaris 2.4
 *
 * Copyright (c) 1994-1995 by Sun MicroSystems, Inc.
 * All rights reserved.
 *
 ****************************************************************/

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>
#include <Xm/Xm.h>
#include <Xm/Protocols.h>

#include "tu_runtime.h"

#include <stdarg.h>

#include <stdio.h>
#include <stdlib.h>
#include "pfgRemote_ui.h"


#include <Xm/Form.h>
#include <Xm/Label.h>
#include <Xm/List.h>
#include <Xm/MessageB.h>
#include <Xm/MwmUtil.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/ScrolledW.h>
#include <Xm/Text.h>
#include <Xm/TextF.h>


/* Local variables used when selecting screen & display */
static Display * sDisplay = NULL;
static Screen  * sScreen  = NULL;

/* forward declaration */
static void class_init(void);

extern void remoteCancelCB(Widget widget,
                           tu_ccb_arg_p closure,
                           XtPointer calldata);
extern void unregister_as_dropsite(Widget widget,
                                   tu_ccb_arg_p closure,
                                   XtPointer calldata);
extern void remoteRemlistCB(Widget widget,
                            tu_ccb_arg_p closure,
                            XtPointer calldata);
extern void remoteRemoveCB(Widget widget,
                           tu_ccb_arg_p closure,
                           XtPointer calldata);
extern void remoteServerCB(Widget widget,
                           tu_ccb_arg_p closure,
                           XtPointer calldata);
extern void remoteTestCB(Widget widget,
                         tu_ccb_arg_p closure,
                         XtPointer calldata);
extern void pfgHelp(Widget widget,
                    XtPointer closure,
                    XtPointer calldata);
extern void remoteAddCB(Widget widget,
                        tu_ccb_arg_p closure,
                        XtPointer calldata);
extern void remoteContinueCB(Widget widget,
                             tu_ccb_arg_p closure,
                             XtPointer calldata);


/****************************************************************
 * get_constraint_widget:
 ****************************************************************/
static Widget get_constraint_widget(Widget child, Widget parent)
{
  Widget w;

  w = child;
  while (XtParent(w) != parent)
    w = XtParent(w);
  return (w);
}


/****************************************************************
 * put_client_data_arg:
 *    set up a client data argument.
 ****************************************************************/
static tu_ccb_arg_p put_client_data_arg(unsigned int cnt, ...)
{
  va_list pvar;
  int i;
  tu_ccb_arg_p rv;

  rv = (tu_ccb_arg_p) malloc(cnt*sizeof(tu_ccb_arg_t));
  if (rv == NULL) return NULL;

  va_start(pvar, cnt);

  for (i=0;i<cnt;i++) {
    rv[i].name = va_arg(pvar, char *);
    rv[i].value = va_arg(pvar, char *);
    rv[i].next = &rv[i+1];
  }
  va_end(pvar);
  rv[cnt-1].next = NULL;
  return rv;
}



/****************************************************************
 * class_init:
 *     Initializes the classes used by the user interface.
 ****************************************************************/
static void class_init(void)
{
  static int inited = 0;

  if (inited != 0)
    return;

  inited = 1;
  sDisplay = sDisplay;

  XtInitializeWidgetClass(xmFormWidgetClass);
  XtInitializeWidgetClass(xmTextWidgetClass);
  XtInitializeWidgetClass(xmLabelWidgetClass);
  XtInitializeWidgetClass(xmTextFieldWidgetClass);
  XtInitializeWidgetClass(xmScrolledWindowWidgetClass);
  XtInitializeWidgetClass(xmRowColumnWidgetClass);
  XtInitializeWidgetClass(xmPushButtonWidgetClass);
  XtInitializeWidgetClass(xmMessageBoxWidgetClass);
}



/****************************************************************
 *
 *  Main C code for presentation component
 *
 ****************************************************************/

/**************************************************************
 * tu_remote_dialog_widget:
 **************************************************************/
Widget tu_remote_dialog_widget(char    * name,
                               Widget    parent,
                               Widget ** warr_ret)
{
  Arg args[27];
  Arg pargs[27];
  Widget tmpw;
  Widget tmpw1;
  Widget widget_array[29];
  XtTranslations ttbl;
  int n;
  int pn;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmFormDialog *****************/
  widget_array[WI_REMOTE_DIALOG] =
    XmCreateFormDialog(parent, name, NULL, 0);

  /***************** panelhelpText : XmText *****************/
  n = 0;
  XtSetArg(args[n], XmNautoShowCursorPosition, False); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  XtSetArg(args[n], XmNeditMode, XmMULTI_LINE_EDIT); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNresizeHeight, True); n++;
  XtSetArg(args[n], XmNwordWrap, True); n++;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  XtSetArg(args[n], XmNmarginWidth, 18); n++;
  XtSetArg(args[n], XmNmarginHeight, 18); n++;
  XtSetArg(args[n], XmNvalue, "message_text"); n++;
  widget_array[WI_PANELHELPTEXT] =
    XmCreateText(widget_array[WI_REMOTE_DIALOG], "panelhelpText", args, n);

  /***************** form : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 20); n++;
  XtSetArg(args[n], XmNmarginHeight, 10); n++;
  widget_array[WI_FORM] =
    XmCreateForm(widget_array[WI_REMOTE_DIALOG], "form", args, n);

  /***************** serverLabelText : XmForm *****************/
  widget_array[WI_SERVERLABELTEXT] =
    XmCreateForm(widget_array[WI_FORM], "serverLabelText", NULL, 0);

  /***************** serverLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_END); n++;
  widget_array[WI_SERVERLABEL] =
    XmCreateLabel(widget_array[WI_SERVERLABELTEXT], "serverLabel", args, n);

  /***************** serverText : XmTextField *****************/
  widget_array[WI_SERVERTEXT] =
    XmCreateTextField(widget_array[WI_SERVERLABELTEXT], "serverText", NULL, 0);

  /***************** ipLabelText : XmForm *****************/
  widget_array[WI_IPLABELTEXT] =
    XmCreateForm(widget_array[WI_FORM], "ipLabelText", NULL, 0);

  /***************** ipLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_END); n++;
  widget_array[WI_IPLABEL] =
    XmCreateLabel(widget_array[WI_IPLABELTEXT], "ipLabel", args, n);

  /***************** ipText : XmTextField *****************/
  widget_array[WI_IPTEXT] =
    XmCreateTextField(widget_array[WI_IPLABELTEXT], "ipText", NULL, 0);

  /***************** filesysLabelText : XmForm *****************/
  widget_array[WI_FILESYSLABELTEXT] =
    XmCreateForm(widget_array[WI_FORM], "filesysLabelText", NULL, 0);

  /***************** filesysLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_END); n++;
  widget_array[WI_FILESYSLABEL] =
    XmCreateLabel(widget_array[WI_FILESYSLABELTEXT], "filesysLabel", args, n);

  /***************** filesysText : XmTextField *****************/
  widget_array[WI_FILESYSTEXT] =
    XmCreateTextField(widget_array[WI_FILESYSLABELTEXT], "filesysText", NULL, 0);

  /***************** remoteList : XmScrolledList *****************/
  n = 0;
  XtSetArg(args[n], XmNscrollBarDisplayPolicy, XmSTATIC); n++;
  XtSetArg(args[n], XmNlistSizePolicy, XmCONSTANT); n++;
  XtSetArg(args[n], XmNvisibleItemCount, 5); n++;
  widget_array[WI_REMOTELIST] =
    XmCreateScrolledList(widget_array[WI_FORM], "remoteList", args, n);

  /***************** mountPointLabelText : XmForm *****************/
  widget_array[WI_MOUNTPOINTLABELTEXT] =
    XmCreateForm(widget_array[WI_FORM], "mountPointLabelText", NULL, 0);

  /***************** mountPointLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_END); n++;
  widget_array[WI_MOUNTPOINTLABEL] =
    XmCreateLabel(widget_array[WI_MOUNTPOINTLABELTEXT], "mountPointLabel", args, n);

  /***************** mountPointText : XmTextField *****************/
  widget_array[WI_MOUNTPOINTTEXT] =
    XmCreateTextField(widget_array[WI_MOUNTPOINTLABELTEXT], "mountPointText", NULL, 0);

  /***************** buttonRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNentryAlignment, XmALIGNMENT_CENTER); n++;
  XtSetArg(args[n], XmNspacing, 10); n++;
  widget_array[WI_BUTTONROWCOLUMN] =
    XmCreateRowColumn(widget_array[WI_FORM], "buttonRowColumn", args, n);

  /***************** addButton : XmPushButton *****************/
  widget_array[WI_ADDBUTTON] =
    XmCreatePushButton(widget_array[WI_BUTTONROWCOLUMN], "addButton", NULL, 0);

  /***************** removeButton : XmPushButton *****************/
  widget_array[WI_REMOVEBUTTON] =
    XmCreatePushButton(widget_array[WI_BUTTONROWCOLUMN], "removeButton", NULL, 0);

  /***************** testButton : XmPushButton *****************/
  widget_array[WI_TESTBUTTON] =
    XmCreatePushButton(widget_array[WI_BUTTONROWCOLUMN], "testButton", NULL, 0);

  /***************** remoteLabel : XmLabel *****************/
  widget_array[WI_REMOTELABEL] =
    XmCreateLabel(widget_array[WI_FORM], "remoteLabel", NULL, 0);

  /***************** summaryList : XmScrolledList *****************/
  n = 0;
  XtSetArg(args[n], XmNvisibleItemCount, 15); n++;
  XtSetArg(args[n], XmNlistSizePolicy, XmCONSTANT); n++;
  XtSetArg(args[n], XmNscrollBarDisplayPolicy, XmSTATIC); n++;
  widget_array[WI_SUMMARYLIST] =
    XmCreateScrolledList(widget_array[WI_FORM], "summaryList", args, n);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdialogType, XmDIALOG_TEMPLATE); n++;
  widget_array[WI_MESSAGEBOX] =
    XmCreateMessageBox(widget_array[WI_REMOTE_DIALOG], "messageBox", args, n);

  /***************** continueButton : XmPushButton *****************/
  widget_array[WI_CONTINUEBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "continueButton", NULL, 0);

  /***************** cancelButton : XmPushButton *****************/
  widget_array[WI_CANCELBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "cancelButton", NULL, 0);

  /***************** helpButton : XmPushButton *****************/
  widget_array[WI_HELPBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "helpButton", NULL, 0);

  /***************** button4 : XmPushButton *****************/
  widget_array[WI_BUTTON4] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "button4", NULL, 0);

  /***************** button5 : XmPushButton *****************/
  widget_array[WI_BUTTON5] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "button5", NULL, 0);

  /* Terminate the widget array */
  widget_array[28] = NULL;


  /***************** panelhelpText : XmText *****************/
  n = 0;
  ttbl = XtParseTranslationTable("#override\n\
~Ctrl ~Meta<BtnDown>:\n\
~Ctrl ~Meta<BtnUp>:");
  XtOverrideTranslations(widget_array[WI_PANELHELPTEXT], ttbl);
  unregister_as_dropsite(widget_array[WI_PANELHELPTEXT],
                         NULL,
                         NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_PANELHELPTEXT], args, n);


  /***************** form : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_PANELHELPTEXT]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_MESSAGEBOX]); n++;
  XtSetValues(widget_array[WI_FORM], args, n);


  /***************** serverLabelText : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SERVERLABELTEXT], args, n);


  /***************** serverLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_SERVERTEXT]); n++;
  XtSetArg(args[n], XmNrightOffset, 5); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_SERVERTEXT]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_SERVERTEXT]); n++;
  XtSetValues(widget_array[WI_SERVERLABEL], args, n);

  XtManageChild(widget_array[WI_SERVERLABEL]);

  /***************** serverText : XmTextField *****************/
  n = 0;
  XtAddCallback(widget_array[WI_SERVERTEXT],
                XmNactivateCallback,
                (XtCallbackProc)remoteServerCB,
                (XtPointer)NULL);

  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SERVERTEXT], args, n);

  XtManageChild(widget_array[WI_SERVERTEXT]);
  XtManageChild(widget_array[WI_SERVERLABELTEXT]);

  /***************** ipLabelText : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_SERVERLABELTEXT]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_SERVERLABELTEXT]); n++;
  XtSetValues(widget_array[WI_IPLABELTEXT], args, n);


  /***************** ipLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_IPTEXT]); n++;
  XtSetArg(args[n], XmNrightOffset, 5); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_IPTEXT]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_IPTEXT]); n++;
  XtSetValues(widget_array[WI_IPLABEL], args, n);

  XtManageChild(widget_array[WI_IPLABEL]);

  /***************** ipText : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_IPTEXT], args, n);

  XtManageChild(widget_array[WI_IPTEXT]);
  XtManageChild(widget_array[WI_IPLABELTEXT]);

  /***************** filesysLabelText : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_IPLABELTEXT]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_IPLABELTEXT]); n++;
  XtSetValues(widget_array[WI_FILESYSLABELTEXT], args, n);


  /***************** filesysLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_FILESYSTEXT]); n++;
  XtSetArg(args[n], XmNrightOffset, 5); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_FILESYSTEXT]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_FILESYSTEXT]); n++;
  XtSetValues(widget_array[WI_FILESYSLABEL], args, n);

  XtManageChild(widget_array[WI_FILESYSLABEL]);

  /***************** filesysText : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_FILESYSTEXT], args, n);

  XtManageChild(widget_array[WI_FILESYSTEXT]);
  XtManageChild(widget_array[WI_FILESYSLABELTEXT]);

  /***************** remoteList : XmScrolledList *****************/
  pn = 0;
  XtAddCallback(widget_array[WI_REMOTELIST],
                XmNbrowseSelectionCallback,
                (XtCallbackProc)remoteRemlistCB,
                (XtPointer)NULL);

  XtSetArg(pargs[pn], XmNtopAttachment, XmATTACH_WIDGET); pn++;
  XtSetArg(pargs[pn], XmNtopWidget, widget_array[WI_FILESYSLABELTEXT]); pn++;
  XtSetArg(pargs[pn], XmNrightAttachment, XmATTACH_OPPOSITE_WIDGET); pn++;
  XtSetArg(pargs[pn], XmNrightWidget, widget_array[WI_FILESYSLABELTEXT]); pn++;
  XtSetArg(pargs[pn], XmNrightOffset, -16); pn++;
  XtSetArg(pargs[pn], XmNbottomAttachment, XmATTACH_WIDGET); pn++;
  XtSetArg(pargs[pn], XmNbottomWidget, widget_array[WI_MOUNTPOINTLABELTEXT]); pn++;
  tmpw = get_constraint_widget(widget_array[WI_REMOTELIST], widget_array[WI_FORM]);
  if (tmpw)
    XtSetValues(tmpw, pargs, pn);

  XtManageChild(widget_array[WI_REMOTELIST]);

  /***************** mountPointLabelText : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_FILESYSLABELTEXT]); n++;
  XtSetValues(widget_array[WI_MOUNTPOINTLABELTEXT], args, n);


  /***************** mountPointLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_MOUNTPOINTTEXT]); n++;
  XtSetArg(args[n], XmNrightOffset, 5); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_MOUNTPOINTTEXT]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_MOUNTPOINTTEXT]); n++;
  XtSetValues(widget_array[WI_MOUNTPOINTLABEL], args, n);

  XtManageChild(widget_array[WI_MOUNTPOINTLABEL]);

  /***************** mountPointText : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MOUNTPOINTTEXT], args, n);

  XtManageChild(widget_array[WI_MOUNTPOINTTEXT]);
  XtManageChild(widget_array[WI_MOUNTPOINTLABELTEXT]);

  /***************** buttonRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  tmpw1 = get_constraint_widget(
widget_array[WI_REMOTELIST], widget_array[WI_FORM]);
  XtSetArg(args[n], XmNleftWidget, tmpw1); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_FILESYSLABELTEXT]); n++;
  XtSetArg(args[n], XmNleftOffset, 10); n++;
  XtSetValues(widget_array[WI_BUTTONROWCOLUMN], args, n);

  XtAddCallback(widget_array[WI_ADDBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)remoteAddCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_ADDBUTTON]);
  XtAddCallback(widget_array[WI_REMOVEBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)remoteRemoveCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_REMOVEBUTTON]);
  XtAddCallback(widget_array[WI_TESTBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)remoteTestCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_TESTBUTTON]);
  XtManageChild(widget_array[WI_BUTTONROWCOLUMN]);

  /***************** remoteLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightOffset, 50); n++;
  XtSetValues(widget_array[WI_REMOTELABEL], args, n);

  XtManageChild(widget_array[WI_REMOTELABEL]);

  /***************** summaryList : XmScrolledList *****************/
  pn = 0;
  XtSetArg(pargs[pn], XmNrightAttachment, XmATTACH_FORM); pn++;
  XtSetArg(pargs[pn], XmNbottomAttachment, XmATTACH_FORM); pn++;
  XtSetArg(pargs[pn], XmNtopAttachment, XmATTACH_WIDGET); pn++;
  XtSetArg(pargs[pn], XmNtopWidget, widget_array[WI_REMOTELABEL]); pn++;
  XtSetArg(pargs[pn], XmNleftAttachment, XmATTACH_WIDGET); pn++;
  XtSetArg(pargs[pn], XmNleftWidget, widget_array[WI_BUTTONROWCOLUMN]); pn++;
  XtSetArg(pargs[pn], XmNleftOffset, 20); pn++;
  tmpw = get_constraint_widget(widget_array[WI_SUMMARYLIST], widget_array[WI_FORM]);
  if (tmpw)
    XtSetValues(tmpw, pargs, pn);

  XtManageChild(widget_array[WI_SUMMARYLIST]);
  XtManageChild(widget_array[WI_FORM]);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdefaultButton, widget_array[WI_CONTINUEBUTTON]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MESSAGEBOX], args, n);

  XtAddCallback(widget_array[WI_CONTINUEBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)remoteContinueCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_CONTINUEBUTTON]);
  XtAddCallback(widget_array[WI_CANCELBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)remoteCancelCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_CANCELBUTTON]);
  XtAddCallback(widget_array[WI_HELPBUTTON],
                XmNactivateCallback,
                pfgHelp,
                (XtPointer)"mount.r");

  XtManageChild(widget_array[WI_HELPBUTTON]);
  XtManageChild(widget_array[WI_MESSAGEBOX]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*29);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*29);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_REMOTE_DIALOG]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_REMOTE_DIALOG]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_REMOTE_DIALOG];
}



/****************************************************************
 * create_method:
 *     This function creates a widget hierarchy using the
 *     functions generated above.
 ****************************************************************/
static Widget create_method(char               * temp,
                            char               * name,
                            Widget               parent,
                            Display            * disp,
                            Screen             * screen,
                            tu_template_descr  * retval)
{
  Widget w;

  sDisplay = disp;
  sScreen = screen;

  /* check each node against its name and call its
   * create function if appropriate */
  w = NULL;
  if (strcmp(temp, "remote_dialog") == 0){
    w = tu_remote_dialog_widget(name, parent, (Widget **)retval);
  }

  sDisplay = NULL;
  sScreen = NULL;
  return w;
}

