
/****************************************************************
 *
 * Name      : pfgSolarCust.c
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.2 / Solaris 2.4
 *
 * Copyright (c) 1994-1995 by Sun MicroSystems, Inc.
 * All rights reserved.
 *
 ****************************************************************/

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>
#include <Xm/Xm.h>
#include <Xm/Protocols.h>

#include "tu_runtime.h"

#include <stdarg.h>

#include <stdio.h>
#include <stdlib.h>
#include "pfgSolarCust_ui.h"


#include <Xm/CascadeB.h>
#include <Xm/CascadeBG.h>
#include <Xm/Form.h>
#include <Xm/Label.h>
#include <Xm/MessageB.h>
#include <Xm/MwmUtil.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/Text.h>
#include <Xm/TextF.h>


/* Local variables used when selecting screen & display */
static Display * sDisplay = NULL;
static Screen  * sScreen  = NULL;

/* forward declaration */
static void class_init(void);

extern void unregister_as_dropsite(Widget widget,
                                   tu_ccb_arg_p closure,
                                   XtPointer calldata);
extern void pfgHelp(Widget widget,
                    XtPointer closure,
                    XtPointer calldata);


/****************************************************************
 * get_constraint_widget:
 ****************************************************************/
static Widget get_constraint_widget(Widget child, Widget parent)
{
  Widget w;

  w = child;
  while (XtParent(w) != parent)
    w = XtParent(w);
  return (w);
}


/****************************************************************
 * put_client_data_arg:
 *    set up a client data argument.
 ****************************************************************/
static tu_ccb_arg_p put_client_data_arg(unsigned int cnt, ...)
{
  va_list pvar;
  int i;
  tu_ccb_arg_p rv;

  rv = (tu_ccb_arg_p) malloc(cnt*sizeof(tu_ccb_arg_t));
  if (rv == NULL) return NULL;

  va_start(pvar, cnt);

  for (i=0;i<cnt;i++) {
    rv[i].name = va_arg(pvar, char *);
    rv[i].value = va_arg(pvar, char *);
    rv[i].next = &rv[i+1];
  }
  va_end(pvar);
  rv[cnt-1].next = NULL;
  return rv;
}



/****************************************************************
 * class_init:
 *     Initializes the classes used by the user interface.
 ****************************************************************/
static void class_init(void)
{
  static int inited = 0;

  if (inited != 0)
    return;

  inited = 1;
  sDisplay = sDisplay;

  XtInitializeWidgetClass(xmFormWidgetClass);
  XtInitializeWidgetClass(xmTextWidgetClass);
  XtInitializeWidgetClass(xmLabelWidgetClass);
  XtInitializeWidgetClass(xmRowColumnWidgetClass);
  XtInitializeWidgetClass(xmMessageBoxWidgetClass);
  XtInitializeWidgetClass(xmPushButtonWidgetClass);
  XtInitializeWidgetClass(xmTextFieldWidgetClass);
}



/****************************************************************
 *
 *  Main C code for presentation component
 *
 ****************************************************************/

/**************************************************************
 * tu_solarcust_dialog_widget:
 **************************************************************/
Widget tu_solarcust_dialog_widget(char    * name,
                                  Widget    parent,
                                  Widget ** warr_ret)
{
  Arg args[26];
  Widget widget_array[25];
  XtTranslations ttbl;
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmFormDialog *****************/
  widget_array[WI_SOLARCUST_DIALOG] =
    XmCreateFormDialog(parent, name, NULL, 0);

  /***************** panelhelpText : XmText *****************/
  n = 0;
  XtSetArg(args[n], XmNautoShowCursorPosition, False); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  XtSetArg(args[n], XmNeditMode, XmMULTI_LINE_EDIT); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNresizeHeight, True); n++;
  XtSetArg(args[n], XmNwordWrap, True); n++;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  XtSetArg(args[n], XmNmarginWidth, 18); n++;
  XtSetArg(args[n], XmNmarginHeight, 18); n++;
  XtSetArg(args[n], XmNvalue, "message_text"); n++;
  widget_array[WI_PANELHELPTEXT] =
    XmCreateText(widget_array[WI_SOLARCUST_DIALOG], "panelhelpText", args, n);

  /***************** solarcustForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  widget_array[WI_SOLARCUSTFORM] =
    XmCreateForm(widget_array[WI_SOLARCUST_DIALOG], "solarcustForm", args, n);

  /***************** fdiskLabelForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNallowOverlap, False); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_FDISKLABELFORM] =
    XmCreateForm(widget_array[WI_SOLARCUSTFORM], "fdiskLabelForm", args, n);

  /***************** fdiskPartitionName : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_FDISKPARTITIONNAME] =
    XmCreateLabel(widget_array[WI_FDISKLABELFORM], "fdiskPartitionName", args, n);

  /***************** fdiskPartitionSize : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNresizable, False); n++;
  widget_array[WI_FDISKPARTITIONSIZE] =
    XmCreateLabel(widget_array[WI_FDISKLABELFORM], "fdiskPartitionSize", args, n);

  /***************** fdiskCylinder : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_END); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_FDISKCYLINDER] =
    XmCreateLabel(widget_array[WI_FDISKLABELFORM], "fdiskCylinder", args, n);

  /***************** fdiskRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNadjustLast, False); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_FDISKROWCOLUMN] =
    XmCreateRowColumn(widget_array[WI_SOLARCUSTFORM], "fdiskRowColumn", args, n);

  /***************** labelRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNentryAlignment, XmALIGNMENT_END); n++;
  widget_array[WI_LABELROWCOLUMN] =
    XmCreateRowColumn(widget_array[WI_SOLARCUSTFORM], "labelRowColumn", args, n);

  /***************** capacityLabel : XmLabel *****************/
  widget_array[WI_CAPACITYLABEL] =
    XmCreateLabel(widget_array[WI_LABELROWCOLUMN], "capacityLabel", NULL, 0);

  /***************** allocatedLabel : XmLabel *****************/
  widget_array[WI_ALLOCATEDLABEL] =
    XmCreateLabel(widget_array[WI_LABELROWCOLUMN], "allocatedLabel", NULL, 0);

  /***************** freeLabel : XmLabel *****************/
  widget_array[WI_FREELABEL] =
    XmCreateLabel(widget_array[WI_LABELROWCOLUMN], "freeLabel", NULL, 0);

  /***************** roundingLabel : XmLabel *****************/
  widget_array[WI_ROUNDINGLABEL] =
    XmCreateLabel(widget_array[WI_LABELROWCOLUMN], "roundingLabel", NULL, 0);

  /***************** sizeRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNentryAlignment, XmALIGNMENT_END); n++;
  widget_array[WI_SIZEROWCOLUMN] =
    XmCreateRowColumn(widget_array[WI_SOLARCUSTFORM], "sizeRowColumn", args, n);

  /***************** capacityValue : XmLabel *****************/
  widget_array[WI_CAPACITYVALUE] =
    XmCreateLabel(widget_array[WI_SIZEROWCOLUMN], "capacityValue", NULL, 0);

  /***************** allocatedValue : XmLabel *****************/
  widget_array[WI_ALLOCATEDVALUE] =
    XmCreateLabel(widget_array[WI_SIZEROWCOLUMN], "allocatedValue", NULL, 0);

  /***************** freeValue : XmLabel *****************/
  widget_array[WI_FREEVALUE] =
    XmCreateLabel(widget_array[WI_SIZEROWCOLUMN], "freeValue", NULL, 0);

  /***************** roundingValue : XmLabel *****************/
  widget_array[WI_ROUNDINGVALUE] =
    XmCreateLabel(widget_array[WI_SIZEROWCOLUMN], "roundingValue", NULL, 0);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdialogType, XmDIALOG_TEMPLATE); n++;
  widget_array[WI_MESSAGEBOX] =
    XmCreateMessageBox(widget_array[WI_SOLARCUST_DIALOG], "messageBox", args, n);

  /***************** okButton : XmPushButton *****************/
  widget_array[WI_OKBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "okButton", NULL, 0);

  /***************** cancelButton : XmPushButton *****************/
  widget_array[WI_CANCELBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "cancelButton", NULL, 0);

  /***************** helpButton : XmPushButton *****************/
  widget_array[WI_HELPBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "helpButton", NULL, 0);

  /***************** button4 : XmPushButton *****************/
  widget_array[WI_BUTTON4] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "button4", NULL, 0);

  /***************** button5 : XmPushButton *****************/
  widget_array[WI_BUTTON5] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "button5", NULL, 0);

  /* Terminate the widget array */
  widget_array[24] = NULL;


  /***************** panelhelpText : XmText *****************/
  n = 0;
  ttbl = XtParseTranslationTable("#override\n\
~Ctrl ~Meta<BtnDown>:\n\
~Ctrl ~Meta<BtnUp>:");
  XtOverrideTranslations(widget_array[WI_PANELHELPTEXT], ttbl);
  unregister_as_dropsite(widget_array[WI_PANELHELPTEXT],
                         NULL,
                         NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_PANELHELPTEXT], args, n);

  XtManageChild(widget_array[WI_PANELHELPTEXT]);

  /***************** solarcustForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_PANELHELPTEXT]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_MESSAGEBOX]); n++;
  XtSetValues(widget_array[WI_SOLARCUSTFORM], args, n);


  /***************** fdiskLabelForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_POSITION); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNleftPosition, 30); n++;
  XtSetValues(widget_array[WI_FDISKLABELFORM], args, n);


  /***************** fdiskPartitionName : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_FDISKPARTITIONNAME], args, n);

  XtManageChild(widget_array[WI_FDISKPARTITIONNAME]);

  /***************** fdiskPartitionSize : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_FDISKPARTITIONNAME]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_FDISKPARTITIONSIZE], args, n);

  XtManageChild(widget_array[WI_FDISKPARTITIONSIZE]);

  /***************** fdiskCylinder : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_FDISKPARTITIONSIZE]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_FDISKCYLINDER], args, n);

  XtManageChild(widget_array[WI_FDISKCYLINDER]);
  XtManageChild(widget_array[WI_FDISKLABELFORM]);

  /***************** fdiskRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_POSITION); n++;
  XtSetArg(args[n], XmNleftPosition, 30); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_FDISKLABELFORM]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_FDISKROWCOLUMN], args, n);

  XtManageChild(widget_array[WI_FDISKROWCOLUMN]);

  /***************** labelRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_POSITION); n++;
  XtSetArg(args[n], XmNrightPosition, 50); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_FDISKROWCOLUMN]); n++;
  XtSetValues(widget_array[WI_LABELROWCOLUMN], args, n);

  XtManageChild(widget_array[WI_CAPACITYLABEL]);
  XtManageChild(widget_array[WI_ALLOCATEDLABEL]);
  XtManageChild(widget_array[WI_FREELABEL]);
  XtManageChild(widget_array[WI_ROUNDINGLABEL]);
  XtManageChild(widget_array[WI_LABELROWCOLUMN]);

  /***************** sizeRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_FDISKROWCOLUMN]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_POSITION); n++;
  XtSetArg(args[n], XmNleftPosition, 50); n++;
  XtSetValues(widget_array[WI_SIZEROWCOLUMN], args, n);

  XtManageChild(widget_array[WI_CAPACITYVALUE]);
  XtManageChild(widget_array[WI_ALLOCATEDVALUE]);
  XtManageChild(widget_array[WI_FREEVALUE]);
  XtManageChild(widget_array[WI_ROUNDINGVALUE]);
  XtManageChild(widget_array[WI_SIZEROWCOLUMN]);
  XtManageChild(widget_array[WI_SOLARCUSTFORM]);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdefaultButton, widget_array[WI_OKBUTTON]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_SOLARCUSTFORM]); n++;
  XtSetValues(widget_array[WI_MESSAGEBOX], args, n);

  XtManageChild(widget_array[WI_OKBUTTON]);
  XtManageChild(widget_array[WI_CANCELBUTTON]);
  XtAddCallback(widget_array[WI_HELPBUTTON],
                XmNactivateCallback,
                pfgHelp,
                (XtPointer)"fdisk.t");

  XtManageChild(widget_array[WI_HELPBUTTON]);
  XtManageChild(widget_array[WI_MESSAGEBOX]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*25);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*25);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_SOLARCUST_DIALOG]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_SOLARCUST_DIALOG]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_SOLARCUST_DIALOG];
}


/**************************************************************
 * tu_fdisk_entry_widget:
 **************************************************************/
Widget tu_fdisk_entry_widget(char    * name,
                             Widget    parent,
                             Widget ** warr_ret)
{
  Arg args[19];
  Widget widget_array[10];
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  widget_array[WI_FDISK_ENTRY] =
    XmCreateForm(parent, name, args, n);

  /***************** fdiskOptionMenu : XmOptionMenu *****************/
  widget_array[WI_FDISKOPTIONMENU] =
    XmCreateOptionMenu(widget_array[WI_FDISK_ENTRY], "fdiskOptionMenu", NULL, 0);

  /***************** pulldownMenu : XmPulldownMenu *****************/
  widget_array[WI_PULLDOWNMENU] =
    XmCreatePulldownMenu(widget_array[WI_FDISK_ENTRY], "pulldownMenu", NULL, 0);
  {
    Arg args[1];
    XtSetArg(args[0], XmNsubMenuId, widget_array[WI_PULLDOWNMENU]);
    XtSetValues(widget_array[WI_FDISKOPTIONMENU], args, 1);
  }

  /***************** solarButton : XmPushButton *****************/
  widget_array[WI_SOLARBUTTON] =
    XmCreatePushButton(widget_array[WI_PULLDOWNMENU], "solarButton", NULL, 0);

  /***************** dosButton : XmPushButton *****************/
  widget_array[WI_DOSBUTTON] =
    XmCreatePushButton(widget_array[WI_PULLDOWNMENU], "dosButton", NULL, 0);

  /***************** unusedButton : XmPushButton *****************/
  widget_array[WI_UNUSEDBUTTON] =
    XmCreatePushButton(widget_array[WI_PULLDOWNMENU], "unusedButton", NULL, 0);

  /***************** otherButton : XmPushButton *****************/
  widget_array[WI_OTHERBUTTON] =
    XmCreatePushButton(widget_array[WI_PULLDOWNMENU], "otherButton", NULL, 0);

  /***************** fdiskSizeText : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNmaxLength, 8); n++;
  XtSetArg(args[n], XmNcolumns, 8); n++;
  XtSetArg(args[n], XmNnavigationType, XmNONE); n++;
  XtSetArg(args[n], XmNresizable, False); n++;
  widget_array[WI_FDISKSIZETEXT] =
    XmCreateTextField(widget_array[WI_FDISK_ENTRY], "fdiskSizeText", args, n);

  /***************** fdiskStartCylinder : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_END); n++;
  XtSetArg(args[n], XmNresizable, False); n++;
  widget_array[WI_FDISKSTARTCYLINDER] =
    XmCreateLabel(widget_array[WI_FDISK_ENTRY], "fdiskStartCylinder", args, n);

  /* Terminate the widget array */
  widget_array[9] = NULL;


  /***************** fdiskOptionMenu : XmOptionMenu *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_FDISKSIZETEXT]); n++;
  XtSetValues(widget_array[WI_FDISKOPTIONMENU], args, n);

  XtManageChild(widget_array[WI_SOLARBUTTON]);
  XtManageChild(widget_array[WI_DOSBUTTON]);
  XtManageChild(widget_array[WI_UNUSEDBUTTON]);
  XtManageChild(widget_array[WI_OTHERBUTTON]);
  XtManageChild(widget_array[WI_FDISKOPTIONMENU]);

  /***************** fdiskSizeText : XmTextField *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_FDISKSTARTCYLINDER]); n++;
  XtSetValues(widget_array[WI_FDISKSIZETEXT], args, n);

  XtManageChild(widget_array[WI_FDISKSIZETEXT]);

  /***************** fdiskStartCylinder : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_FDISKSTARTCYLINDER], args, n);

  XtManageChild(widget_array[WI_FDISKSTARTCYLINDER]);
  XtManageChild(widget_array[WI_FDISK_ENTRY]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*10);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*10);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_FDISK_ENTRY]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_FDISK_ENTRY]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_FDISK_ENTRY];
}



/****************************************************************
 * create_method:
 *     This function creates a widget hierarchy using the
 *     functions generated above.
 ****************************************************************/
static Widget create_method(char               * temp,
                            char               * name,
                            Widget               parent,
                            Display            * disp,
                            Screen             * screen,
                            tu_template_descr  * retval)
{
  Widget w;

  sDisplay = disp;
  sScreen = screen;

  /* check each node against its name and call its
   * create function if appropriate */
  w = NULL;
  if (strcmp(temp, "solarcust_dialog") == 0){
    w = tu_solarcust_dialog_widget(name, parent, (Widget **)retval);
  }
  else if (strcmp(temp, "fdisk_entry") == 0){
    w = tu_fdisk_entry_widget(name, parent, (Widget **)retval);
  }

  sDisplay = NULL;
  sScreen = NULL;
  return w;
}

