
/****************************************************************
 *
 * Name      : pfgSummary.c
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.2 / Solaris 2.4
 *
 * Copyright (c) 1994-1995 by Sun MicroSystems, Inc.
 * All rights reserved.
 *
 ****************************************************************/

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>
#include <Xm/Xm.h>
#include <Xm/Protocols.h>

#include "tu_runtime.h"

#include <stdarg.h>

#include <stdio.h>
#include <stdlib.h>
#include "pfgSummary_ui.h"


#include <Xm/Form.h>
#include <Xm/Label.h>
#include <Xm/MessageB.h>
#include <Xm/MwmUtil.h>
#include <Xm/PushB.h>
#include <Xm/ScrolledW.h>
#include <Xm/Text.h>


/* Local variables used when selecting screen & display */
static Display * sDisplay = NULL;
static Screen  * sScreen  = NULL;

/* forward declaration */
static void class_init(void);

extern void summaryContinueCB(Widget widget,
                              tu_ccb_arg_p closure,
                              XtPointer calldata);
extern void pfgExit(Widget widget,
                    tu_ccb_arg_p closure,
                    XtPointer calldata);
extern void unregister_as_dropsite(Widget widget,
                                   tu_ccb_arg_p closure,
                                   XtPointer calldata);
extern void diskcheckerrorOkCB(Widget widget,
                               tu_ccb_arg_p closure,
                               XtPointer calldata);
extern void diskcheckerrorCancelCB(Widget widget,
                                   tu_ccb_arg_p closure,
                                   XtPointer calldata);
extern void pfgHelp(Widget widget,
                    XtPointer closure,
                    XtPointer calldata);
extern void summaryChangeCB(Widget widget,
                            tu_ccb_arg_p closure,
                            XtPointer calldata);


/****************************************************************
 * get_constraint_widget:
 ****************************************************************/
static Widget get_constraint_widget(Widget child, Widget parent)
{
  Widget w;

  w = child;
  while (XtParent(w) != parent)
    w = XtParent(w);
  return (w);
}


/****************************************************************
 * put_client_data_arg:
 *    set up a client data argument.
 ****************************************************************/
static tu_ccb_arg_p put_client_data_arg(unsigned int cnt, ...)
{
  va_list pvar;
  int i;
  tu_ccb_arg_p rv;

  rv = (tu_ccb_arg_p) malloc(cnt*sizeof(tu_ccb_arg_t));
  if (rv == NULL) return NULL;

  va_start(pvar, cnt);

  for (i=0;i<cnt;i++) {
    rv[i].name = va_arg(pvar, char *);
    rv[i].value = va_arg(pvar, char *);
    rv[i].next = &rv[i+1];
  }
  va_end(pvar);
  rv[cnt-1].next = NULL;
  return rv;
}



/****************************************************************
 * class_init:
 *     Initializes the classes used by the user interface.
 ****************************************************************/
static void class_init(void)
{
  static int inited = 0;

  if (inited != 0)
    return;

  inited = 1;
  sDisplay = sDisplay;

  XtInitializeWidgetClass(xmFormWidgetClass);
  XtInitializeWidgetClass(xmTextWidgetClass);
  XtInitializeWidgetClass(xmLabelWidgetClass);
  XtInitializeWidgetClass(xmScrolledWindowWidgetClass);
  XtInitializeWidgetClass(xmMessageBoxWidgetClass);
  XtInitializeWidgetClass(xmPushButtonWidgetClass);
}



/****************************************************************
 *
 *  Main C code for presentation component
 *
 ****************************************************************/

/**************************************************************
 * tu_summary_dialog_widget:
 **************************************************************/
Widget tu_summary_dialog_widget(char    * name,
                                Widget    parent,
                                Widget ** warr_ret)
{
  Arg args[29];
  Widget widget_array[13];
  XtTranslations ttbl;
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmFormDialog *****************/
  n = 0;
  XtSetArg(args[n], XmNrubberPositioning, False); n++;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  widget_array[WI_SUMMARY_DIALOG] =
    XmCreateFormDialog(parent, name, args, n);

  /***************** panelhelpText : XmText *****************/
  n = 0;
  XtSetArg(args[n], XmNautoShowCursorPosition, False); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  XtSetArg(args[n], XmNeditMode, XmMULTI_LINE_EDIT); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNresizeHeight, True); n++;
  XtSetArg(args[n], XmNwordWrap, True); n++;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  XtSetArg(args[n], XmNmarginWidth, 18); n++;
  XtSetArg(args[n], XmNmarginHeight, 18); n++;
  XtSetArg(args[n], XmNvalue, "message_text"); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_PANELHELPTEXT] =
    XmCreateText(widget_array[WI_SUMMARY_DIALOG], "panelhelpText", args, n);

  /***************** summaryForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNresizePolicy, XmRESIZE_ANY); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SUMMARYFORM] =
    XmCreateForm(widget_array[WI_SUMMARY_DIALOG], "summaryForm", args, n);

  /***************** profileLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_BEGINNING); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_PROFILELABEL] =
    XmCreateLabel(widget_array[WI_SUMMARYFORM], "profileLabel", args, n);

  /***************** summaryScrolledWindow : XmScrolledWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNscrollingPolicy, XmAUTOMATIC); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_SUMMARYSCROLLEDWINDOW] =
    XmCreateScrolledWindow(widget_array[WI_SUMMARYFORM], "summaryScrolledWindow", args, n);

  /***************** summaryLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_BEGINNING); n++;
  widget_array[WI_SUMMARYLABEL] =
    XmCreateLabel(widget_array[WI_SUMMARYSCROLLEDWINDOW], "summaryLabel", args, n);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdialogType, XmDIALOG_TEMPLATE); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_MESSAGEBOX] =
    XmCreateMessageBox(widget_array[WI_SUMMARY_DIALOG], "messageBox", args, n);

  /***************** continueButton : XmPushButton *****************/
  widget_array[WI_CONTINUEBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "continueButton", NULL, 0);

  /***************** changeButton : XmPushButton *****************/
  widget_array[WI_CHANGEBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "changeButton", NULL, 0);

  /***************** exitButton : XmPushButton *****************/
  widget_array[WI_EXITBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "exitButton", NULL, 0);

  /***************** helpButton : XmPushButton *****************/
  widget_array[WI_HELPBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "helpButton", NULL, 0);

  /***************** button5 : XmPushButton *****************/
  widget_array[WI_BUTTON5] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "button5", NULL, 0);

  /* Terminate the widget array */
  widget_array[12] = NULL;


  /***************** object of type : XmFormDialog *****************/
  n = 0;
  XtSetArg(args[n], XmNinitialFocus, widget_array[WI_CONTINUEBUTTON]); n++;
  XtSetArg(args[n], XmNdefaultButton, widget_array[WI_CONTINUEBUTTON]); n++;
  XtSetValues(widget_array[WI_SUMMARY_DIALOG], args, n);


  /***************** panelhelpText : XmText *****************/
  n = 0;
  ttbl = XtParseTranslationTable("#override\n\
~Ctrl ~Meta<BtnDown>:\n\
~Ctrl ~Meta<BtnUp>:");
  XtOverrideTranslations(widget_array[WI_PANELHELPTEXT], ttbl);
  unregister_as_dropsite(widget_array[WI_PANELHELPTEXT],
                         NULL,
                         NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_MESSAGEBOX]); n++;
  XtSetValues(widget_array[WI_PANELHELPTEXT], args, n);

  XtManageChild(widget_array[WI_PANELHELPTEXT]);

  /***************** summaryForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_PANELHELPTEXT]); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_MESSAGEBOX]); n++;
  XtSetArg(args[n], XmNleftOffset, 10); n++;
  XtSetArg(args[n], XmNrightOffset, 10); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_PANELHELPTEXT]); n++;
  XtSetValues(widget_array[WI_SUMMARYFORM], args, n);


  /***************** profileLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_PROFILELABEL], args, n);

  XtManageChild(widget_array[WI_PROFILELABEL]);

  /***************** summaryScrolledWindow : XmScrolledWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_PROFILELABEL]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SUMMARYSCROLLEDWINDOW], args, n);

  XtManageChild(widget_array[WI_SUMMARYLABEL]);
  XtManageChild(widget_array[WI_SUMMARYSCROLLEDWINDOW]);
  XtManageChild(widget_array[WI_SUMMARYFORM]);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdefaultButton, widget_array[WI_CONTINUEBUTTON]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_MESSAGEBOX], args, n);

  XtAddCallback(widget_array[WI_CONTINUEBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)summaryContinueCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_CONTINUEBUTTON]);
  XtAddCallback(widget_array[WI_CHANGEBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)summaryChangeCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_CHANGEBUTTON]);
  XtAddCallback(widget_array[WI_EXITBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)pfgExit,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_EXITBUTTON]);
  XtAddCallback(widget_array[WI_HELPBUTTON],
                XmNactivateCallback,
                pfgHelp,
                (XtPointer)"initial.t");

  XtManageChild(widget_array[WI_HELPBUTTON]);
  XtManageChild(widget_array[WI_MESSAGEBOX]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*13);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*13);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_SUMMARY_DIALOG]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_SUMMARY_DIALOG]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_SUMMARY_DIALOG];
}


/**************************************************************
 * tu_scrolled_error_window_widget:
 **************************************************************/
Widget tu_scrolled_error_window_widget(char    * name,
                                       Widget    parent,
                                       Widget ** warr_ret)
{
  Arg args[28];
  Arg pargs[28];
  Widget tmpw;
  Widget tmpw1;
  Widget widget_array[10];
  XtTranslations ttbl;
  int n;
  int pn;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmFormDialog *****************/
  n = 0;
  XtSetArg(args[n], XmNnoResize, True); n++;
  XtSetArg(args[n], XmNdialogStyle, XmDIALOG_PRIMARY_APPLICATION_MODAL); n++;
  widget_array[WI_SCROLLED_ERROR_WINDOW] =
    XmCreateFormDialog(parent, name, args, n);

  /***************** panelhelpText : XmText *****************/
  n = 0;
  XtSetArg(args[n], XmNautoShowCursorPosition, False); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  XtSetArg(args[n], XmNeditMode, XmMULTI_LINE_EDIT); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNresizeHeight, True); n++;
  XtSetArg(args[n], XmNwordWrap, True); n++;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  XtSetArg(args[n], XmNmarginWidth, 18); n++;
  XtSetArg(args[n], XmNmarginHeight, 18); n++;
  XtSetArg(args[n], XmNvalue, "message_text"); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_PANELHELPTEXT1] =
    XmCreateText(widget_array[WI_SCROLLED_ERROR_WINDOW], "panelhelpText", args, n);

  /***************** scrolledText : XmScrolledText *****************/
  n = 0;
  pn = 0;
  XtSetArg(args[n], XmNscrollHorizontal, False); n++;
  XtSetArg(args[n], XmNheight, 175); n++;
  XtSetArg(args[n], XmNwidth, 500); n++;
  XtSetArg(args[n], XmNeditable, False); n++;
  XtSetArg(pargs[pn], XmNscrolledWindowMarginWidth, 18); pn++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  XtSetArg(args[n], XmNwordWrap, True); n++;
  XtSetArg(args[n], XmNeditMode, XmMULTI_LINE_EDIT); n++;
  XtSetArg(pargs[pn], XmNresizable, False); pn++;
  widget_array[WI_SCROLLEDTEXT] =
    XmCreateScrolledText(widget_array[WI_SCROLLED_ERROR_WINDOW], "scrolledText", args, n);
  tmpw = get_constraint_widget(widget_array[WI_SCROLLEDTEXT], widget_array[WI_SCROLLED_ERROR_WINDOW]);
  if (tmpw)
    XtSetValues(tmpw, pargs, pn);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdialogType, XmDIALOG_TEMPLATE); n++;
  XtSetArg(args[n], XmNresizable, True); n++;
  widget_array[WI_MESSAGEBOX1] =
    XmCreateMessageBox(widget_array[WI_SCROLLED_ERROR_WINDOW], "messageBox", args, n);

  /***************** errorOkbutton : XmPushButton *****************/
  widget_array[WI_ERROROKBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX1], "errorOkbutton", NULL, 0);

  /***************** errorCancelbutton : XmPushButton *****************/
  n = 0;
  XtSetArg(args[n], XmNshowAsDefault, 1); n++;
  widget_array[WI_ERRORCANCELBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX1], "errorCancelbutton", args, n);

  /***************** button3 : XmPushButton *****************/
  widget_array[WI_BUTTON3] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX1], "button3", NULL, 0);

  /***************** button4 : XmPushButton *****************/
  widget_array[WI_BUTTON4] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX1], "button4", NULL, 0);

  /***************** button5 : XmPushButton *****************/
  widget_array[WI_BUTTON6] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX1], "button5", NULL, 0);

  /* Terminate the widget array */
  widget_array[9] = NULL;


  /***************** object of type : XmFormDialog *****************/
  n = 0;
  XtSetArg(args[n], XmNdefaultButton, widget_array[WI_ERRORCANCELBUTTON]); n++;
  XtSetArg(args[n], XmNinitialFocus, widget_array[WI_MESSAGEBOX1]); n++;
  XtAddEventHandler(widget_array[WI_SCROLLED_ERROR_WINDOW],
                    StructureNotifyMask, False,
                    tu_set_kbd_focus,
                    (XtPointer)widget_array[WI_MESSAGEBOX1]);
  XtSetValues(widget_array[WI_SCROLLED_ERROR_WINDOW], args, n);


  /***************** panelhelpText : XmText *****************/
  n = 0;
  ttbl = XtParseTranslationTable("#override\n\
~Ctrl ~Meta<BtnDown>:\n\
~Ctrl ~Meta<BtnUp>:");
  XtOverrideTranslations(widget_array[WI_PANELHELPTEXT1], ttbl);
  unregister_as_dropsite(widget_array[WI_PANELHELPTEXT1],
                         NULL,
                         NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE); n++;
  XtSetValues(widget_array[WI_PANELHELPTEXT1], args, n);

  XtManageChild(widget_array[WI_PANELHELPTEXT1]);

  /***************** scrolledText : XmScrolledText *****************/
  pn = 0;
  XtSetArg(pargs[pn], XmNleftAttachment, XmATTACH_FORM); pn++;
  XtSetArg(pargs[pn], XmNrightAttachment, XmATTACH_FORM); pn++;
  XtSetArg(pargs[pn], XmNtopAttachment, XmATTACH_WIDGET); pn++;
  XtSetArg(pargs[pn], XmNtopWidget, widget_array[WI_PANELHELPTEXT1]); pn++;
  XtSetArg(pargs[pn], XmNbottomAttachment, XmATTACH_NONE); pn++;
  tmpw = get_constraint_widget(widget_array[WI_SCROLLEDTEXT], widget_array[WI_SCROLLED_ERROR_WINDOW]);
  if (tmpw)
    XtSetValues(tmpw, pargs, pn);

  XtManageChild(widget_array[WI_SCROLLEDTEXT]);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdefaultButton, widget_array[WI_ERRORCANCELBUTTON]); n++;
  XtSetArg(args[n], XmNinitialFocus, widget_array[WI_ERRORCANCELBUTTON]); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  tmpw1 = get_constraint_widget(
widget_array[WI_SCROLLEDTEXT], widget_array[WI_SCROLLED_ERROR_WINDOW]);
  XtSetArg(args[n], XmNtopWidget, tmpw1); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MESSAGEBOX1], args, n);

  XtAddCallback(widget_array[WI_ERROROKBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)diskcheckerrorOkCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_ERROROKBUTTON]);
  XtAddCallback(widget_array[WI_ERRORCANCELBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)diskcheckerrorCancelCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_ERRORCANCELBUTTON]);
  XtManageChild(widget_array[WI_MESSAGEBOX1]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*10);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*10);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_SCROLLED_ERROR_WINDOW]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_SCROLLED_ERROR_WINDOW]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_SCROLLED_ERROR_WINDOW];
}



/****************************************************************
 * create_method:
 *     This function creates a widget hierarchy using the
 *     functions generated above.
 ****************************************************************/
static Widget create_method(char               * temp,
                            char               * name,
                            Widget               parent,
                            Display            * disp,
                            Screen             * screen,
                            tu_template_descr  * retval)
{
  Widget w;

  sDisplay = disp;
  sScreen = screen;

  /* check each node against its name and call its
   * create function if appropriate */
  w = NULL;
  if (strcmp(temp, "summary_dialog") == 0){
    w = tu_summary_dialog_widget(name, parent, (Widget **)retval);
  }
  else if (strcmp(temp, "scrolled_error_window") == 0){
    w = tu_scrolled_error_window_widget(name, parent, (Widget **)retval);
  }

  sDisplay = NULL;
  sScreen = NULL;
  return w;
}

