
/****************************************************************
 *
 * Name      : pfgSoftware.c
 *
 * File is generated by TeleUSE
 * Version : TeleUSE v3.0.2 / Solaris 2.4
 *
 * Copyright (c) 1994-1995 by Sun MicroSystems, Inc.
 * All rights reserved.
 *
 ****************************************************************/

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>
#include <Xm/Xm.h>
#include <Xm/Protocols.h>

#include "tu_runtime.h"

#include <stdarg.h>

#include <stdio.h>
#include <stdlib.h>
#include "pfgSoftware_ui.h"


#include <Xm/ArrowB.h>
#include <Xm/Form.h>
#include <Xm/Frame.h>
#include <Xm/Label.h>
#include <Xm/List.h>
#include <Xm/MessageB.h>
#include <Xm/MwmUtil.h>
#include <Xm/PanedW.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/ScrolledW.h>
#include <Xm/Text.h>


/* Local variables used when selecting screen & display */
static Display * sDisplay = NULL;
static Screen  * sScreen  = NULL;

/* forward declaration */
static void class_init(void);

extern void unregister_as_dropsite(Widget widget,
                                   tu_ccb_arg_p closure,
                                   XtPointer calldata);
extern void softwareOkCB(Widget widget,
                         tu_ccb_arg_p closure,
                         XtPointer calldata);
extern void pfgHelp(Widget widget,
                    XtPointer closure,
                    XtPointer calldata);


/****************************************************************
 * get_constraint_widget:
 ****************************************************************/
static Widget get_constraint_widget(Widget child, Widget parent)
{
  Widget w;

  w = child;
  while (XtParent(w) != parent)
    w = XtParent(w);
  return (w);
}


/****************************************************************
 * put_client_data_arg:
 *    set up a client data argument.
 ****************************************************************/
static tu_ccb_arg_p put_client_data_arg(unsigned int cnt, ...)
{
  va_list pvar;
  int i;
  tu_ccb_arg_p rv;

  rv = (tu_ccb_arg_p) malloc(cnt*sizeof(tu_ccb_arg_t));
  if (rv == NULL) return NULL;

  va_start(pvar, cnt);

  for (i=0;i<cnt;i++) {
    rv[i].name = va_arg(pvar, char *);
    rv[i].value = va_arg(pvar, char *);
    rv[i].next = &rv[i+1];
  }
  va_end(pvar);
  rv[cnt-1].next = NULL;
  return rv;
}



/****************************************************************
 * class_init:
 *     Initializes the classes used by the user interface.
 ****************************************************************/
static void class_init(void)
{
  static int inited = 0;

  if (inited != 0)
    return;

  inited = 1;
  sDisplay = sDisplay;

  XtInitializeWidgetClass(xmFormWidgetClass);
  XtInitializeWidgetClass(xmTextWidgetClass);
  XtInitializeWidgetClass(xmLabelWidgetClass);
  XtInitializeWidgetClass(xmScrolledWindowWidgetClass);
  XtInitializeWidgetClass(xmRowColumnWidgetClass);
  XtInitializeWidgetClass(xmFrameWidgetClass);
  XtInitializeWidgetClass(xmArrowButtonWidgetClass);
  XtInitializeWidgetClass(xmPushButtonWidgetClass);
  XtInitializeWidgetClass(xmPanedWindowWidgetClass);
  XtInitializeWidgetClass(xmMessageBoxWidgetClass);
}



/****************************************************************
 *
 *  Main C code for presentation component
 *
 ****************************************************************/

/**************************************************************
 * tu_software_dialog_widget:
 **************************************************************/
Widget tu_software_dialog_widget(char    * name,
                                 Widget    parent,
                                 Widget ** warr_ret)
{
  Arg args[27];
  Widget widget_array[58];
  XmString xms;
  XtTranslations ttbl;
  int n;
  /* Make sure the classes used are initialized */
  class_init();

  /***************** object of type : XmFormDialog *****************/
  widget_array[WI_SOFTWARE_DIALOG] =
    XmCreateFormDialog(parent, name, NULL, 0);

  /***************** panelhelpText : XmText *****************/
  n = 0;
  XtSetArg(args[n], XmNautoShowCursorPosition, False); n++;
  XtSetArg(args[n], XmNcursorPositionVisible, False); n++;
  XtSetArg(args[n], XmNeditMode, XmMULTI_LINE_EDIT); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNresizeHeight, True); n++;
  XtSetArg(args[n], XmNwordWrap, True); n++;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  XtSetArg(args[n], XmNmarginWidth, 18); n++;
  XtSetArg(args[n], XmNmarginHeight, 18); n++;
  XtSetArg(args[n], XmNvalue, "message_text"); n++;
  widget_array[WI_PANELHELPTEXT] =
    XmCreateText(widget_array[WI_SOFTWARE_DIALOG], "panelhelpText", args, n);

  /***************** softwareForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNmarginWidth, 20); n++;
  XtSetArg(args[n], XmNmarginHeight, 10); n++;
  widget_array[WI_SOFTWAREFORM] =
    XmCreateForm(widget_array[WI_SOFTWARE_DIALOG], "softwareForm", args, n);

  /***************** clusterLabel : XmLabel *****************/
  widget_array[WI_CLUSTERLABEL] =
    XmCreateLabel(widget_array[WI_SOFTWAREFORM], "clusterLabel", NULL, 0);

  /***************** sizeLabel : XmLabel *****************/
  widget_array[WI_SIZELABEL] =
    XmCreateLabel(widget_array[WI_SOFTWAREFORM], "sizeLabel", NULL, 0);

  /***************** packagesScrolledWindow : XmScrolledWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNscrollingPolicy, XmAUTOMATIC); n++;
  widget_array[WI_PACKAGESSCROLLEDWINDOW] =
    XmCreateScrolledWindow(widget_array[WI_SOFTWAREFORM], "packagesScrolledWindow", args, n);

  /***************** softwareClustersRowColumn : XmRowColumn *****************/
  widget_array[WI_SOFTWARECLUSTERSROWCOLUMN] =
    XmCreateRowColumn(widget_array[WI_PACKAGESSCROLLEDWINDOW], "softwareClustersRowColumn", NULL, 0);

  /***************** totalSizeForm : XmForm *****************/
  widget_array[WI_TOTALSIZEFORM] =
    XmCreateForm(widget_array[WI_SOFTWAREFORM], "totalSizeForm", NULL, 0);

  /***************** totalSizeLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_END); n++;
  widget_array[WI_TOTALSIZELABEL] =
    XmCreateLabel(widget_array[WI_TOTALSIZEFORM], "totalSizeLabel", args, n);

  /***************** totalSizeValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_BEGINNING); n++;
  widget_array[WI_TOTALSIZEVALUE] =
    XmCreateLabel(widget_array[WI_TOTALSIZEFORM], "totalSizeValue", args, n);

  /***************** legendFrame : XmFrame *****************/
  n = 0;
  XtSetArg(args[n], XmNshadowType, XmSHADOW_ETCHED_OUT); n++;
  widget_array[WI_LEGENDFRAME] =
    XmCreateFrame(widget_array[WI_SOFTWAREFORM], "legendFrame", args, n);

  /***************** legendForm : XmForm *****************/
  widget_array[WI_LEGENDFORM] =
    XmCreateForm(widget_array[WI_LEGENDFRAME], "legendForm", NULL, 0);

  /***************** legendRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNentryAlignment, XmALIGNMENT_END); n++;
  XtSetArg(args[n], XmNnumColumns, 3); n++;
  XtSetArg(args[n], XmNpacking, XmPACK_COLUMN); n++;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNadjustLast, False); n++;
  widget_array[WI_LEGENDROWCOLUMN] =
    XmCreateRowColumn(widget_array[WI_LEGENDFORM], "legendRowColumn", args, n);

  /***************** expandForm : XmForm *****************/
  widget_array[WI_EXPANDFORM] =
    XmCreateForm(widget_array[WI_LEGENDROWCOLUMN], "expandForm", NULL, 0);

  /***************** expandLegendArrow : XmArrowButton *****************/
  n = 0;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  XtSetArg(args[n], XmNarrowDirection, XmARROW_DOWN); n++;
  widget_array[WI_EXPANDLEGENDARROW] =
    XmCreateArrowButton(widget_array[WI_EXPANDFORM], "expandLegendArrow", args, n);

  /***************** expandLegendLabel : XmLabel *****************/
  widget_array[WI_EXPANDLEGENDLABEL] =
    XmCreateLabel(widget_array[WI_EXPANDFORM], "expandLegendLabel", NULL, 0);

  /***************** contractForm : XmForm *****************/
  widget_array[WI_CONTRACTFORM] =
    XmCreateForm(widget_array[WI_LEGENDROWCOLUMN], "contractForm", NULL, 0);

  /***************** contractLegendArrow : XmArrowButton *****************/
  n = 0;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  XtSetArg(args[n], XmNarrowDirection, XmARROW_RIGHT); n++;
  widget_array[WI_CONTRACTLEGENDARROW] =
    XmCreateArrowButton(widget_array[WI_CONTRACTFORM], "contractLegendArrow", args, n);

  /***************** contractLegendLabel : XmLabel *****************/
  widget_array[WI_CONTRACTLEGENDLABEL] =
    XmCreateLabel(widget_array[WI_CONTRACTFORM], "contractLegendLabel", NULL, 0);

  /***************** requiredForm : XmForm *****************/
  widget_array[WI_REQUIREDFORM] =
    XmCreateForm(widget_array[WI_LEGENDROWCOLUMN], "requiredForm", NULL, 0);

  /***************** requiredLegendButton : XmPushButton *****************/
  n = 0;
  XtSetArg(args[n], XmNlabelType, XmPIXMAP); n++;
  XtSetArg(args[n], XmNwidth, 20); n++;
  XtSetArg(args[n], XmNheight, 20); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNmarginHeight, 0); n++;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  XtSetArg(args[n], XmNresizable, False); n++;
  widget_array[WI_REQUIREDLEGENDBUTTON] =
    XmCreatePushButton(widget_array[WI_REQUIREDFORM], "requiredLegendButton", args, n);

  /***************** requiredLegendLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_BEGINNING); n++;
  widget_array[WI_REQUIREDLEGENDLABEL] =
    XmCreateLabel(widget_array[WI_REQUIREDFORM], "requiredLegendLabel", args, n);

  /***************** partialForm : XmForm *****************/
  widget_array[WI_PARTIALFORM] =
    XmCreateForm(widget_array[WI_LEGENDROWCOLUMN], "partialForm", NULL, 0);

  /***************** partialLegendButton : XmPushButton *****************/
  n = 0;
  XtSetArg(args[n], XmNlabelType, XmPIXMAP); n++;
  XtSetArg(args[n], XmNwidth, 20); n++;
  XtSetArg(args[n], XmNheight, 20); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNmarginHeight, 0); n++;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  XtSetArg(args[n], XmNresizable, False); n++;
  widget_array[WI_PARTIALLEGENDBUTTON] =
    XmCreatePushButton(widget_array[WI_PARTIALFORM], "partialLegendButton", args, n);

  /***************** partialLegendLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_BEGINNING); n++;
  widget_array[WI_PARTIALLEGENDLABEL] =
    XmCreateLabel(widget_array[WI_PARTIALFORM], "partialLegendLabel", args, n);

  /***************** selectedform : XmForm *****************/
  widget_array[WI_SELECTEDFORM] =
    XmCreateForm(widget_array[WI_LEGENDROWCOLUMN], "selectedform", NULL, 0);

  /***************** selectedLegendButton : XmPushButton *****************/
  n = 0;
  XtSetArg(args[n], XmNlabelType, XmPIXMAP); n++;
  XtSetArg(args[n], XmNwidth, 20); n++;
  XtSetArg(args[n], XmNheight, 20); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNmarginHeight, 0); n++;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  XtSetArg(args[n], XmNresizable, False); n++;
  widget_array[WI_SELECTEDLEGENDBUTTON] =
    XmCreatePushButton(widget_array[WI_SELECTEDFORM], "selectedLegendButton", args, n);

  /***************** selectedLegendLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_BEGINNING); n++;
  widget_array[WI_SELECTEDLEGENDLABEL] =
    XmCreateLabel(widget_array[WI_SELECTEDFORM], "selectedLegendLabel", args, n);

  /***************** unselectedForm : XmForm *****************/
  widget_array[WI_UNSELECTEDFORM] =
    XmCreateForm(widget_array[WI_LEGENDROWCOLUMN], "unselectedForm", NULL, 0);

  /***************** unselectedLegendButton : XmPushButton *****************/
  n = 0;
  XtSetArg(args[n], XmNlabelType, XmPIXMAP); n++;
  XtSetArg(args[n], XmNwidth, 20); n++;
  XtSetArg(args[n], XmNheight, 20); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  XtSetArg(args[n], XmNmarginHeight, 0); n++;
  XtSetArg(args[n], XmNrecomputeSize, False); n++;
  XtSetArg(args[n], XmNresizable, False); n++;
  widget_array[WI_UNSELECTEDLEGENDBUTTON] =
    XmCreatePushButton(widget_array[WI_UNSELECTEDFORM], "unselectedLegendButton", args, n);

  /***************** unselectedLegendLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNalignment, XmALIGNMENT_BEGINNING); n++;
  widget_array[WI_UNSELECTEDLEGENDLABEL] =
    XmCreateLabel(widget_array[WI_UNSELECTEDFORM], "unselectedLegendLabel", args, n);

  /***************** softwarePanedWindow : XmPanedWindow *****************/
  widget_array[WI_SOFTWAREPANEDWINDOW] =
    XmCreatePanedWindow(widget_array[WI_SOFTWAREFORM], "softwarePanedWindow", NULL, 0);

  /***************** softwareInfoFrame : XmFrame *****************/
  n = 0;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  widget_array[WI_SOFTWAREINFOFRAME] =
    XmCreateFrame(widget_array[WI_SOFTWAREPANEDWINDOW], "softwareInfoFrame", args, n);

  /***************** softwareInfoLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNchildType, XmFRAME_TITLE_CHILD); n++;
  widget_array[WI_SOFTWAREINFOLABEL] =
    XmCreateLabel(widget_array[WI_SOFTWAREINFOFRAME], "softwareInfoLabel", args, n);

  /***************** softwareInfoScrolledWindow : XmScrolledWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNtraversalOn, False); n++;
  XtSetArg(args[n], XmNvisualPolicy, XmCONSTANT); n++;
  XtSetArg(args[n], XmNscrollingPolicy, XmAUTOMATIC); n++;
  widget_array[WI_SOFTWAREINFOSCROLLEDWINDOW] =
    XmCreateScrolledWindow(widget_array[WI_SOFTWAREINFOFRAME], "softwareInfoScrolledWindow", args, n);

  /***************** softwareInfoForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNverticalSpacing, 3); n++;
  widget_array[WI_SOFTWAREINFOFORM] =
    XmCreateForm(widget_array[WI_SOFTWAREINFOSCROLLEDWINDOW], "softwareInfoForm", args, n);

  /***************** softwareInfoRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNentryAlignment, XmALIGNMENT_END); n++;
  XtSetArg(args[n], XmNpacking, XmPACK_TIGHT); n++;
  XtSetArg(args[n], XmNmarginHeight, 0); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  widget_array[WI_SOFTWAREINFOROWCOLUMN] =
    XmCreateRowColumn(widget_array[WI_SOFTWAREINFOFORM], "softwareInfoRowColumn", args, n);

  /***************** prodLabel : XmLabel *****************/
  n = 0;
  xms = tu_cvt_string_to_xmstring(" ");
  XtSetArg(args[n], XmNlabelString, xms); n++;
  widget_array[WI_PRODLABEL] =
    XmCreateLabel(widget_array[WI_SOFTWAREINFOROWCOLUMN], "prodLabel", args, n);

  if (xms) XmStringFree(xms);

  /***************** abbrevLabel : XmLabel *****************/
  n = 0;
  xms = tu_cvt_string_to_xmstring(" ");
  XtSetArg(args[n], XmNlabelString, xms); n++;
  widget_array[WI_ABBREVLABEL] =
    XmCreateLabel(widget_array[WI_SOFTWAREINFOROWCOLUMN], "abbrevLabel", args, n);

  if (xms) XmStringFree(xms);

  /***************** vendorLabel : XmLabel *****************/
  n = 0;
  xms = tu_cvt_string_to_xmstring(" ");
  XtSetArg(args[n], XmNlabelString, xms); n++;
  widget_array[WI_VENDORLABEL] =
    XmCreateLabel(widget_array[WI_SOFTWAREINFOROWCOLUMN], "vendorLabel", args, n);

  if (xms) XmStringFree(xms);

  /***************** descriptLabel : XmLabel *****************/
  n = 0;
  xms = tu_cvt_string_to_xmstring(" ");
  XtSetArg(args[n], XmNlabelString, xms); n++;
  widget_array[WI_DESCRIPTLABEL] =
    XmCreateLabel(widget_array[WI_SOFTWAREINFOROWCOLUMN], "descriptLabel", args, n);

  if (xms) XmStringFree(xms);

  /***************** estLabel : XmLabel *****************/
  n = 0;
  xms = tu_cvt_string_to_xmstring(" ");
  XtSetArg(args[n], XmNlabelString, xms); n++;
  widget_array[WI_ESTLABEL] =
    XmCreateLabel(widget_array[WI_SOFTWAREINFOROWCOLUMN], "estLabel", args, n);

  if (xms) XmStringFree(xms);

  /***************** softwareInfoRowColumn1 : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNpacking, XmPACK_TIGHT); n++;
  XtSetArg(args[n], XmNmarginHeight, 0); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  widget_array[WI_SOFTWAREINFOROWCOLUMN1] =
    XmCreateRowColumn(widget_array[WI_SOFTWAREINFOFORM], "softwareInfoRowColumn1", args, n);

  /***************** prodValue : XmLabel *****************/
  n = 0;
  xms = tu_cvt_string_to_xmstring(" ");
  XtSetArg(args[n], XmNlabelString, xms); n++;
  widget_array[WI_PRODVALUE] =
    XmCreateLabel(widget_array[WI_SOFTWAREINFOROWCOLUMN1], "prodValue", args, n);

  if (xms) XmStringFree(xms);

  /***************** abbrevValue : XmLabel *****************/
  n = 0;
  xms = tu_cvt_string_to_xmstring(" ");
  XtSetArg(args[n], XmNlabelString, xms); n++;
  widget_array[WI_ABBREVVALUE] =
    XmCreateLabel(widget_array[WI_SOFTWAREINFOROWCOLUMN1], "abbrevValue", args, n);

  if (xms) XmStringFree(xms);

  /***************** vendorValue : XmLabel *****************/
  n = 0;
  xms = tu_cvt_string_to_xmstring(" ");
  XtSetArg(args[n], XmNlabelString, xms); n++;
  widget_array[WI_VENDORVALUE] =
    XmCreateLabel(widget_array[WI_SOFTWAREINFOROWCOLUMN1], "vendorValue", args, n);

  if (xms) XmStringFree(xms);

  /***************** descriptValue : XmLabel *****************/
  n = 0;
  xms = tu_cvt_string_to_xmstring(" ");
  XtSetArg(args[n], XmNlabelString, xms); n++;
  widget_array[WI_DESCRIPTVALUE] =
    XmCreateLabel(widget_array[WI_SOFTWAREINFOROWCOLUMN1], "descriptValue", args, n);

  if (xms) XmStringFree(xms);

  /***************** sizeRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNnumColumns, 2); n++;
  XtSetArg(args[n], XmNpacking, XmPACK_COLUMN); n++;
  XtSetArg(args[n], XmNmarginHeight, 0); n++;
  XtSetArg(args[n], XmNmarginWidth, 0); n++;
  widget_array[WI_SIZEROWCOLUMN] =
    XmCreateRowColumn(widget_array[WI_SOFTWAREINFOROWCOLUMN1], "sizeRowColumn", args, n);

  /***************** softwareDependenciesFrame : XmFrame *****************/
  n = 0;
  XtSetArg(args[n], XmNshadowThickness, 0); n++;
  widget_array[WI_SOFTWAREDEPENDENCIESFRAME] =
    XmCreateFrame(widget_array[WI_SOFTWAREPANEDWINDOW], "softwareDependenciesFrame", args, n);

  /***************** softwareDependenciesScrolledList : XmScrolledList *****************/
  n = 0;
  XtSetArg(args[n], XmNvisibleItemCount, 4); n++;
  widget_array[WI_SOFTWAREDEPENDENCIESSCROLLEDLIST] =
    XmCreateScrolledList(widget_array[WI_SOFTWAREDEPENDENCIESFRAME], "softwareDependenciesScrolledList", args, n);

  /***************** softwareDependenciesLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNchildType, XmFRAME_TITLE_CHILD); n++;
  widget_array[WI_SOFTWAREDEPENDENCIESLABEL] =
    XmCreateLabel(widget_array[WI_SOFTWAREDEPENDENCIESFRAME], "softwareDependenciesLabel", args, n);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdialogType, XmDIALOG_TEMPLATE); n++;
  widget_array[WI_MESSAGEBOX] =
    XmCreateMessageBox(widget_array[WI_SOFTWARE_DIALOG], "messageBox", args, n);

  /***************** okButton : XmPushButton *****************/
  widget_array[WI_OKBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "okButton", NULL, 0);

  /***************** helpButton : XmPushButton *****************/
  widget_array[WI_HELPBUTTON] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "helpButton", NULL, 0);

  /***************** button3 : XmPushButton *****************/
  widget_array[WI_BUTTON3] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "button3", NULL, 0);

  /***************** button4 : XmPushButton *****************/
  widget_array[WI_BUTTON4] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "button4", NULL, 0);

  /***************** button5 : XmPushButton *****************/
  widget_array[WI_BUTTON5] =
    XmCreatePushButton(widget_array[WI_MESSAGEBOX], "button5", NULL, 0);

  /* Terminate the widget array */
  widget_array[57] = NULL;


  /***************** panelhelpText : XmText *****************/
  n = 0;
  ttbl = XtParseTranslationTable("#override\n\
~Ctrl ~Meta<BtnDown>:\n\
~Ctrl ~Meta<BtnUp>:");
  XtOverrideTranslations(widget_array[WI_PANELHELPTEXT], ttbl);
  unregister_as_dropsite(widget_array[WI_PANELHELPTEXT],
                         NULL,
                         NULL);

  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_PANELHELPTEXT], args, n);


  /***************** softwareForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_PANELHELPTEXT]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_MESSAGEBOX]); n++;
  XtSetValues(widget_array[WI_SOFTWAREFORM], args, n);


  /***************** clusterLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_CLUSTERLABEL], args, n);

  XtManageChild(widget_array[WI_CLUSTERLABEL]);

  /***************** sizeLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_PACKAGESSCROLLEDWINDOW]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_PACKAGESSCROLLEDWINDOW]); n++;
  XtSetValues(widget_array[WI_SIZELABEL], args, n);

  XtManageChild(widget_array[WI_SIZELABEL]);

  /***************** packagesScrolledWindow : XmScrolledWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopWidget, widget_array[WI_CLUSTERLABEL]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_TOTALSIZEFORM]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_TOTALSIZEFORM]); n++;
  XtSetValues(widget_array[WI_PACKAGESSCROLLEDWINDOW], args, n);

  XtManageChild(widget_array[WI_SOFTWARECLUSTERSROWCOLUMN]);
  XtManageChild(widget_array[WI_PACKAGESSCROLLEDWINDOW]);

  /***************** totalSizeForm : XmForm *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNbottomWidget, widget_array[WI_LEGENDFRAME]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_OPPOSITE_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_LEGENDFRAME]); n++;
  XtSetValues(widget_array[WI_TOTALSIZEFORM], args, n);


  /***************** totalSizeLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNrightWidget, widget_array[WI_TOTALSIZEVALUE]); n++;
  XtSetValues(widget_array[WI_TOTALSIZELABEL], args, n);

  XtManageChild(widget_array[WI_TOTALSIZELABEL]);

  /***************** totalSizeValue : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_TOTALSIZEVALUE], args, n);

  XtManageChild(widget_array[WI_TOTALSIZEVALUE]);
  XtManageChild(widget_array[WI_TOTALSIZEFORM]);

  /***************** legendFrame : XmFrame *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_LEGENDFRAME], args, n);


  /***************** expandLegendArrow : XmArrowButton *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_EXPANDLEGENDARROW], args, n);

  XtManageChild(widget_array[WI_EXPANDLEGENDARROW]);

  /***************** expandLegendLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_EXPANDLEGENDARROW]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_EXPANDLEGENDLABEL], args, n);

  XtManageChild(widget_array[WI_EXPANDLEGENDLABEL]);
  XtManageChild(widget_array[WI_EXPANDFORM]);

  /***************** contractLegendArrow : XmArrowButton *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_CONTRACTLEGENDARROW], args, n);

  XtManageChild(widget_array[WI_CONTRACTLEGENDARROW]);

  /***************** contractLegendLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_CONTRACTLEGENDARROW]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_CONTRACTLEGENDLABEL], args, n);

  XtManageChild(widget_array[WI_CONTRACTLEGENDLABEL]);
  XtManageChild(widget_array[WI_CONTRACTFORM]);

  /***************** requiredLegendButton : XmPushButton *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftOffset, 30); n++;
  XtSetValues(widget_array[WI_REQUIREDLEGENDBUTTON], args, n);

  XtManageChild(widget_array[WI_REQUIREDLEGENDBUTTON]);

  /***************** requiredLegendLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_REQUIREDLEGENDBUTTON]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_REQUIREDLEGENDLABEL], args, n);

  XtManageChild(widget_array[WI_REQUIREDLEGENDLABEL]);
  XtManageChild(widget_array[WI_REQUIREDFORM]);

  /***************** partialLegendButton : XmPushButton *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftOffset, 30); n++;
  XtSetValues(widget_array[WI_PARTIALLEGENDBUTTON], args, n);

  XtManageChild(widget_array[WI_PARTIALLEGENDBUTTON]);

  /***************** partialLegendLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_PARTIALLEGENDBUTTON]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_PARTIALLEGENDLABEL], args, n);

  XtManageChild(widget_array[WI_PARTIALLEGENDLABEL]);
  XtManageChild(widget_array[WI_PARTIALFORM]);

  /***************** selectedLegendButton : XmPushButton *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftOffset, 30); n++;
  XtSetValues(widget_array[WI_SELECTEDLEGENDBUTTON], args, n);

  XtManageChild(widget_array[WI_SELECTEDLEGENDBUTTON]);

  /***************** selectedLegendLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_SELECTEDLEGENDBUTTON]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SELECTEDLEGENDLABEL], args, n);

  XtManageChild(widget_array[WI_SELECTEDLEGENDLABEL]);
  XtManageChild(widget_array[WI_SELECTEDFORM]);

  /***************** unselectedLegendButton : XmPushButton *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftOffset, 30); n++;
  XtSetValues(widget_array[WI_UNSELECTEDLEGENDBUTTON], args, n);

  XtManageChild(widget_array[WI_UNSELECTEDLEGENDBUTTON]);

  /***************** unselectedLegendLabel : XmLabel *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_UNSELECTEDLEGENDBUTTON]); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_UNSELECTEDLEGENDLABEL], args, n);

  XtManageChild(widget_array[WI_UNSELECTEDLEGENDLABEL]);
  XtManageChild(widget_array[WI_UNSELECTEDFORM]);
  XtManageChild(widget_array[WI_LEGENDROWCOLUMN]);
  XtManageChild(widget_array[WI_LEGENDFORM]);
  XtManageChild(widget_array[WI_LEGENDFRAME]);

  /***************** softwarePanedWindow : XmPanedWindow *****************/
  n = 0;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_PACKAGESSCROLLEDWINDOW]); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftOffset, 20); n++;
  XtSetValues(widget_array[WI_SOFTWAREPANEDWINDOW], args, n);

  XtManageChild(widget_array[WI_SOFTWAREINFOLABEL]);

  /***************** softwareInfoRowColumn : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SOFTWAREINFOROWCOLUMN], args, n);

  XtManageChild(widget_array[WI_PRODLABEL]);
  XtManageChild(widget_array[WI_ABBREVLABEL]);
  XtManageChild(widget_array[WI_VENDORLABEL]);
  XtManageChild(widget_array[WI_DESCRIPTLABEL]);
  XtManageChild(widget_array[WI_ESTLABEL]);
  XtManageChild(widget_array[WI_SOFTWAREINFOROWCOLUMN]);

  /***************** softwareInfoRowColumn1 : XmRowColumn *****************/
  n = 0;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_WIDGET); n++;
  XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftWidget, widget_array[WI_SOFTWAREINFOROWCOLUMN]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_SOFTWAREINFOROWCOLUMN1], args, n);

  XtManageChild(widget_array[WI_PRODVALUE]);
  XtManageChild(widget_array[WI_ABBREVVALUE]);
  XtManageChild(widget_array[WI_VENDORVALUE]);
  XtManageChild(widget_array[WI_DESCRIPTVALUE]);
  XtManageChild(widget_array[WI_SIZEROWCOLUMN]);
  XtManageChild(widget_array[WI_SOFTWAREINFOROWCOLUMN1]);
  XtManageChild(widget_array[WI_SOFTWAREINFOFORM]);
  XtManageChild(widget_array[WI_SOFTWAREINFOSCROLLEDWINDOW]);
  XtManageChild(widget_array[WI_SOFTWAREINFOFRAME]);
  XtManageChild(widget_array[WI_SOFTWAREDEPENDENCIESSCROLLEDLIST]);
  XtManageChild(widget_array[WI_SOFTWAREDEPENDENCIESLABEL]);
  XtManageChild(widget_array[WI_SOFTWAREDEPENDENCIESFRAME]);
  XtManageChild(widget_array[WI_SOFTWAREPANEDWINDOW]);
  XtManageChild(widget_array[WI_SOFTWAREFORM]);

  /***************** messageBox : XmMessageBox *****************/
  n = 0;
  XtSetArg(args[n], XmNdefaultButton, widget_array[WI_OKBUTTON]); n++;
  XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM); n++;
  XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM); n++;
  XtSetValues(widget_array[WI_MESSAGEBOX], args, n);

  XtAddCallback(widget_array[WI_OKBUTTON],
                XmNactivateCallback,
                (XtCallbackProc)softwareOkCB,
                (XtPointer)NULL);

  XtManageChild(widget_array[WI_OKBUTTON]);
  XtAddCallback(widget_array[WI_HELPBUTTON],
                XmNactivateCallback,
                pfgHelp,
                (XtPointer)"spotsoftcust.r");

  XtManageChild(widget_array[WI_HELPBUTTON]);
  XtManageChild(widget_array[WI_MESSAGEBOX]);

  /*
   *  Allocate memory for the widget array to return
   */
  if (warr_ret != NULL) {
    *warr_ret = (Widget *) malloc(sizeof(Widget)*58);
    (void) memcpy((char *)*warr_ret,
                  (char *)widget_array,
           sizeof(Widget)*58);
  }

  /*
   *   Fix for SMI's X/NeWS server
   */
  tu_ol_fix_hierarchy(widget_array[WI_SOFTWARE_DIALOG]);

  /*
   *   Invoke the create callbacks
   */
  tu_widcre_invoke_hooks(widget_array[WI_SOFTWARE_DIALOG]);

  /*
   *   Return the first created widget.
   */
  return widget_array[WI_SOFTWARE_DIALOG];
}



/****************************************************************
 * create_method:
 *     This function creates a widget hierarchy using the
 *     functions generated above.
 ****************************************************************/
static Widget create_method(char               * temp,
                            char               * name,
                            Widget               parent,
                            Display            * disp,
                            Screen             * screen,
                            tu_template_descr  * retval)
{
  Widget w;

  sDisplay = disp;
  sScreen = screen;

  /* check each node against its name and call its
   * create function if appropriate */
  w = NULL;
  if (strcmp(temp, "software_dialog") == 0){
    w = tu_software_dialog_widget(name, parent, (Widget **)retval);
  }

  sDisplay = NULL;
  sScreen = NULL;
  return w;
}

